- artifactory/commands/generic/deleteprops.go
- artifactory/commands/generic/setprops.go
Set props command could have returned a none (nill) error instead of the totalLengthErr
that occurred.
The failCount of delete props command was not set in case of returning an error.
For consistency it is now set before the return error statement like in the set props command logic.
> Set/Delete props unified errors output (#823)

- artifactory/commands/generic/upload.go
Because build properties (i.e Build name, number and VCS url) shouldn't be set with
multiple values it was decided to pass them separately.
Fixes https://github.com/jfrog/jfrog-cli/issues/786
> Separate build related properties from other properties

- artifactory/commands/generic/download.go
- artifactory/commands/generic/upload.go
-----
This PR fixes an issue, which causes the displayed summary for upload and download commands to get corrupted., as shown below. This fix requires an addition PR to the https://github.com/jfrog/jfrog-cli repository.
```
$ jfrog rt dl generic-local/*dd* aa/ --threads 30
Log path: /Users/eyalb/.jfrog/logs/jfrog-cli.2020-10-06.14-04-30.39948.log
Working...  \                    
{
"status": "success",
"totals": {
"success": 1,
"failure": 0
Log path: /Users/eyalb/.jfrog/logs/jfrog-cli.2020-10-06.14-04-30.39948.log
```
> Bug fix - Command summary gets cut by the progress bar

- utils/config/config.go
Refreshable tokens are disabled when working with external tools (build tools, curl, etc) or when sending requests not via ArtifactoryHttpClient.
This PR adds a fix to disable refreshable tokens both when using and the default server, and when a specified one.
> Add refreshable tokens exclusion for default server

- artifactory/commands/mvn/mvn.go
-----
This PR is targeting the following issue: https://www.jfrog.com/jira/browse/BI-533
Resolution from Artifactory is not always enforced due to missing `buildInfoConfig.artifactoryResolutionEnabled=true` system variable, same as we do in Jenkins: https://github.com/jfrog/jenkins-artifactory-plugin/blob/artifactory-3.8.1/src/main/java/org/jfrog/hudson/pipeline/common/executors/MavenExecutor.java#L68
> Bugfix - Maven resolution from Artifactory issue

- utils/config/config.go
- utils/config/config_test.go
- utils/config/encryption.go
- utils/config/testdata/config/encryption/jfrog-cli.conf.v4
- utils/coreutils/utils.go
For now on the converted config version will be saved in new file with a name
matching the version. This will allow backward compatibility for multiple CLI
proceses.
-----
> Upgrade config version

- artifactory/utils/pip/installer.go
-----
Resolves: https://github.com/jfrog/jfrog-cli/issues/879
In order to collect the build info in pip install commands, we parse the pip-install build logs. To parse the downloaded file trace, we expect the following regex:
> ^\s\sDownloading\s[^\s]*\/packages\/[^\s]*\/([^\s]*)
Trace example using a remote Pypi registry:
>  Downloading http://127.0.0.1:8081/artifactory/api/pypi/pypi/packages/packages/ca/4d/7d59d82b777f3f7a1128608195655a1b36c1de89c292363d53d52d92a807/npm-0.1.1.tar.gz
However when using an Artifactory's local repository, we don't have the "packages" word in the trace:
>  Downloading http://127.0.0.1:8081/artifactory/api/pypi/pypi/ca/4d/7d59d82b777f3f7a1128608195655a1b36c1de89c292363d53d52d92a807/npm-0.1.1.tar.gz (2.5 kB) (edited)
> Bugfix - pip-install does not support local repos

- go.mod
- go.sum
-----
Handle errors during build of the JFrog CLI in Linux:
> ./build/build.sh   
> \# github.com/c-bata/c
> ../../go/pkg/mod/github.com/c-bata/go-prompt@v0.2.3/input_posix.go:66:45: cannot use &t.origTermios (type *syscall.Termios) as type *unix.Termios in argument to termios.Tcgetattr
> ../../go/pkg/mod/github.com/c-bata/go-prompt@v0.2.3/input_posix.go:74:52: cannot use &n (type *syscall.Termios) as type *unix.Termios in argument to termios.Tcsetattr
> ../../go/pkg/mod/github.com/c-bata/go-prompt@v0.2.3/input_posix.go:82:59: cannot use &t.origTermios (type *syscall.Termios) as type *unix.Termios in argument to termios.Tcsetattr 
For more information, see https://github.com/c-bata/go-prompt/pull/191
> Update go-prompt to 0.2.5

- plugins/commonutils.go
-----
Add infrastructure for adding common plugins utils.
Add 2 common utils:
1. GetServerIdFlag - Get the `server-id` common flag.
2. GetRtDetails - Get the Artifactory Details of the provided 'server-id', or the default one
> Add plugins common utils

- artifactory/commands/testdata/jfrog-cli.conf
- tests/jfrogclicore_test.go
- utils/config/config_test.go
- utils/tests/utils.go
-----
1. Prevent TestGetArtifactoriesFromConfig from overriding current CLI servers configurations - configure JFROG_HOME before the test starts.
2. Prevent TestRtDetailsFromConfigFile from creating jfrog-cli.conf.v4 file - upgrade test configuration from v3 to v4.
> Improve conf tests

- artifactory/utils/container/buildinfo.go
- artifactory/utils/container/containermanager.go
-----
Docker/Podman fail to set props on layers in virtual repositories. This fix will set the layers props on the local repository instead.
> Bugfix - docker push fails to set props for virtual repositories

- artifactory/commands/pip/install.go
-----
Fixes https://github.com/jfrog/jfrog-cli/issues/948
This PR resolves 2 issues:
1. When setup.py does not exist in CWD, running `jfrog rt pipi <package-name> --build-name=<buildName> --build-number=<buildNumber>` will fail with "Could not find setup.py file in current directory". Only when the `-r` flag provided, the execution didn't fail. The preferred behavior should be: If setup.py does not exist, always use the build name as the module name.
2. When setup.py does exist in CWD, running `jfrog rt pipi <package-name> --build-name=<buildName> --build-number=<buildNumber> -r requirements.txt` will set the module name as the build-name, although it has a setup.py file.
> Allow running pip install without setup.py

- artifactory/commands/npm/publish.go
-----
Fixes the following unreleased bug, which was detected by the npm tests:
When publishing an npm package to Artifactory, the package is deployed without the build.name, build.number and build.timestamp props.
This caused the following tests failures:
```
[Info] [Command] jfrog rt npmp cli-tests-npm-1611824469 --npm-args= --build-name=cli-tests-npm-build-1611824469 --build-number=9 --module=jfrog-test
[Warn] You are using a deprecated syntax of the "npmp" command.
To use the new syntax, the command expects the details of the Artifactory server and repositories to be pre-configured.
To create this configuration, run the following command from the root directory of the project:
$ jfrog rt npmc
This will create the configuration inside the .jfrog directory under the root directory of the …
```
> Unreleased bug - npm-publish not adding build props

- artifactory/commands/buildinfo/adddependencies.go
- artifactory/commands/buildinfo/addgit.go
- artifactory/commands/buildinfo/addgit_test.go
- artifactory/commands/buildinfo/buildappend.go
- artifactory/commands/buildinfo/clean.go
- artifactory/commands/buildinfo/collectenv.go
- artifactory/commands/buildinfo/publish.go
- artifactory/commands/buildinfo/xrayscan.go
- artifactory/commands/container/buildcreate.go
- artifactory/commands/container/pull.go
- artifactory/commands/container/push.go
- artifactory/commands/dotnet/dotnetcommand.go
- artifactory/commands/generic/download.go
- artifactory/commands/generic/upload.go
- artifactory/commands/golang/go.go
- artifactory/commands/golang/gopublish.go
- artifactory/commands/gradle/gradle.go
- artifactory/commands/mvn/mvn.go
- artifactory/commands/npm/installorci.go
- artifactory/commands/npm/publish.go
- artifactory/commands/pip/install.go
- artifactory/utils/argsutils.go
- artifactory/utils/buildinfoproperties.go
- artifactory/utils/buildinfoproperties_test.go
- artifactory/utils/buildutils.go
- artifactory/utils/container/buildinfo.go
- artifactory/utils/golang/project/project.go
- go.mod
- go.sum
-----
This PR adds support for the new Projects functionality in Artifactory. It relies on https://github.com/jfrog/jfrog-client-go/pull/283 to be merged before first.
1. The build-publish command now accpets an optional "project" flag, with the project key value. If provided, the build-info is published to the project's build-info repository, named my-project-key-build-info. If not provided, the build-info is published (by default) to a repository named artifactory-build-info.
2. All commands which deploy files to Artifactory also accpet the new "project" flag. They use it to add a new "build.repo" property on each of the deployed artifacts, in addition to the existing "build.name", "build.number" and "build.timestamp" props. The "build.repo" prop stores the name of the build-info …
> Support for Artifactory Projects

- artifactory/commands/buildinfo/addgit.go
- artifactory/commands/buildinfo/addgit_test.go
Following [jfrog/jfrog-cli#858](https://github.com/jfrog/jfrog-cli/issues/858)
> BuildAddGit - ignore error when revision does not exist in range

- common/commands/config.go
-----
Resolves https://github.com/jfrog/jfrog-cli/issues/980
* Prompt for SSH passphrase if the key is encrypted or the SSH key path leads to a key not yet exist.
* Fix log messages - the config logs should not suggest providing `--ssh-key-path` or `--ssh-passphrase` in CLI commands.
> Prompt for ssh passphrase in configuration

- common/commands/config.go
- common/commands/config_test.go
- utils/config/config.go
- utils/config/config_test.go
-----
* Change pipelines URL key in the configuration from `pipelines` to `pipelinesUrl`
* After providing the platform URL, mission control endpoint should be `/mc` and not `missioncontrol`.
> Config - fix pipelines key and default mc URL

- common/commands/config.go
-----
Remove ping to Artifactory after configuring access token using the config command.
This is necessary to allow configuring non-Artifactory JFrog services with access tokens that don't have permission to Artifactory.
> Remove access token validation in config

- artifactory/commands/buildinfo/buildappend.go
- artifactory/utils/buildutils.go
-----
This PR depends on https://github.com/jfrog/jfrog-client-go/pull/303.
It removes the addition of the "build.repo" attached property, since it is not required by Artifactory.
> Remove the addition of the "build.repo" attached prop

- artifactory/utils/dependenciesutils.go
-----
When downloading the Maven and Gradle build-info-extractors JARs, the URL is the platform URL, but should be Artifactory URL.
> Bugfix - Incorrect custom BI extractors URL

- artifactory/commands/gradle/gradle.go
- artifactory/commands/gradle/gradle_test.go
- artifactory/commands/mvn/mvn.go
- artifactory/commands/mvn/mvn_test.go
- artifactory/utils/dependenciesutils.go
-----
Following Bintray sunset, we should download Maven and Gradle build-info extractors JARs from `https://oss.jfrog.org/artifactory` instead of from JCenter.
This PR introduce the following changes:
1. Introduce `JFROG_CLI_EXTRACTORS_REMOTE`. This env var in form of ServerID/RemoteRepo.
2. Deprecate `JFROG_CLI_JCENTER_REMOTE_SERVER` and suggest to use `JFROG_CLI_EXTRACTORS_REMOTE` instead.
3.  * If `JFROG_CLI_JCENTER_REMOTE_SERVER` and `JFROG_CLI_EXTRACTORS_REMOTE` are not set, download JARs from  https://oss.jfrog.org/artifactory.
* If `JFROG_CLI_JCENTER_REMOTE_SERVER` is set - use it and `JFROG_CLI_JCENTER_REMOTE_REPO` as before and print a warning message. Following this error message, it is the user's responsibility to change the remote repository URL from …
> Download build-info extractors from ojo

- artifactory/commands/gradle/gradle.go
- artifactory/commands/mvn/mvn.go
- artifactory/utils/dependenciesutils.go
-----
Thie PR is a follow-up to #102.
Following JCenter sunset, we stopped publishing the build-info extractors. Therefore, the version in JCenter is not the latest.
If `JFROG_CLI_JCENTER_REMOTE_SERVER` deprecated env var is set, use Maven extractor 2.23.0 instead of 2.25.0 and Gradle extractor 4.21.0 instead of 4.23.0.
> Use different extractors version when using JCenter

- utils/config/configtoken.go
- utils/config/configtoken_test.go
-----
Currently, when importing tokens created by JFrog CLI < 1.44, the URLs are incorrect.
To fix it, this PR is suggesting the following on importing an old token:
```go
token.ArtifactoryUrl = token.Url
token.Url = ""
```
> Fix config import from old server tokens

- artifactory/commands/container/containermanager.go
Before the fix
```
./jfrog-cli rt dp nginx:latest test-sguproject-docker
nginx:latest
panic: runtime error: slice bounds out of range [-1:]
goroutine 1 [running]:
github.com/jfrog/jfrog-cli-core/artifactory/commands/container.(*ContainerManagerCommand).SetImageTag(0xc0002f5cc0, 0x7ffeefbff8e2, 0xc, 0x4)
/Users/sguiheux/pkg/mod/github.com/jfrog/jfrog-cli-core@v1.4.2/artifactory/commands/container/containermanager.go:26 +0x14a
github.com/jfrog/jfrog-cli/artifactory.containerPushCmd(0xc0001ed340, 0x0, 0xc000268e58, 0x15cdecd)
/Users/sguiheux/src/github.com/jfrog/jfrog-cli/artifactory/cli.go:1350 +0x29f
github.com/jfrog/jfrog-cli/artifactory.GetCommands.func27(0xc0001ed340, 0x0, 0xc0001ed340)
/Users/sguiheux/src/github.com/jfrog/jfrog-cli/artifactory/cli.go:471 +0x34 …
```
> fix: avoid panic on wrong image tag

- artifactory/commands/npm/installorci.go
-----
In npm 7, running npm ls produces a flat dependency tree with direct dependencies only (see https://github.com/npm/cli/blob/v7.0.0/CHANGELOG.md#npm-ls).
To get the transitive dependency tree as in versions prior to 6, we should add the --all flag.
Fortunately, npm commands do not fail when providing unknown flags. Therefore we can add the --all flag also when running with npm<7.
> Bugfix - npmi on version 7 builds flat dep tree

- artifactory/commands/dotnet/dotnetcommand.go
- artifactory/utils/dotnet/configfiletemplate.go
-----
Added support for protocolVersion in generated NuGet.config file to enable support for NuGet v3 feed.
Removed support for building NuGet.config using native dotnet tool as it doesn't support configuring protocolVersion.
> Fix dotnet nuget config missing protocolVersion attribute (#98)

- artifactory/utils/dotnet/dependencies/assetsjson.go
- artifactory/utils/dotnet/solution/solution.go
-----
It was found that multiple .Net projects in the same directory may be interpret wrong by our gathering dependencies sources logic. The logic was changed to avoid such cases.
> Fix .Net dependencies source interpretation

- artifactory/commands/gradle/gradle.go
- artifactory/commands/mvn/mvn.go
- artifactory/utils/container/containermanager.go
-----
The “jfrog rt mvn/gradle/docker/go-publish” commands' output reaches into stdout and therefore gets mixed with the detailed summary.
This commit fixes this by redirect all the buildtools log into stderr.
Related PR: https://github.com/jfrog/gofrog/pull/18
> External process redirect the stdout to stderr

- artifactory/commands/gradle/gradle.go
- artifactory/commands/mvn/mvn.go
- utils/gradle/utils.go
- utils/gradle/utils_test.go
- utils/mvn/utils.go
- utils/mvn/utils_test.go
- xray/commands/audit/gradle.go
- xray/commands/audit/mvn.go
-----
* Move Gradle and Maven utils from common/commands to package utils.
* Update build info extractors versions to 2.28.4/4.24.10.
> Refactor Maven and Gradle utils

- artifactory/utils/buildinfoproperties.go
-----
Deployable artifact file path on windows contain backslashes which interpreter as special characters. As a result, the path gets corrupted.
To fix this we encode all backslashes.
> Bugfix - Detailed summary doesn't print for maven/gradle builds

- utils/gradle/utils.go
- utils/mvn/utils.go
- xray/commands/audit/javautils.go
- xray/commands/audit/npm.go
-----
* Fix an issue whereby stderr and stdout closed after executing the Maven and Gradle commands. As a result, prints to the logs were invisible.
* Print audit results in the npm, Gradle, and Maven audit when there are no vulnerabilities/licenses/violations. For example:
```
jfrog xr audit-gradle --licenses
```
```
jfrog xr audit-gradle --watches=all
```
> Improve audit output

- artifactory/commands/gradle/gradle.go
- artifactory/commands/mvn/mvn.go
- artifactory/utils/container/containermanager.go
-----
Following this [commit](https://github.com/jfrog/jfrog-cli-core/commit/f1279f082f8cafb85c0336199d3645c6e8dc26b8), external processes close the stderr stream. As a result, the first process runs and closes the stderr stream and the next process' messages won't be print
> Bugfix - External processes hide log messages

- artifactory/commands/gradle/gradle.go
- artifactory/commands/mvn/mvn.go
-----
Accessing gc.serverDetails and mc.serverDetails directly, produces nil pointer dereference.
Instead we should retrieve the server details by gc.ServerDetails() and mc.ServerDetails().
> Bugfix - unmarshalDeployableArtifacts produces NPD

- common/commands/command.go
-----
Report usage should not run if there is no Artifactory URL configured.
> Report usage should run only if there is rt url

- common/commands/config.go
- common/commands/config_test.go
- go.mod
- go.sum
- utils/config/config.go
- utils/ioutils/ioutils.go
-----
* Currently SSH connection is only allowed on Artifactory. When the user provides SSH platform URL, we should populate Artifactory's URL with this SSH URL.
* Username, password, and access tokens should not be provided when SSH URL is provided.
* SSH passphrase should be displayed (as `***`) when running `jfrog c show`.
* Upgrade crypto to the latest
> v1: Improve ssh usability

- artifactory/spec/specfiles.go
-----
* Remove restriction about using --archive and --symlinks together.
* The combination of --archive, --symlinks and --explode together is still forbidden. 
When uploading a symlink to Artifactory, the symlink is represented in Artifactory as 0 size file with properties 
describing the symlink. This symlink representation is not yet supported by Artifactory when exploding symlinks from a zip.
> V1: Archiving symlinks in upload command

- common/spec/specfiles.go
- go.mod
- go.sum
-----
* Remove restriction about using --archive and --symlinks together.
* The combination of --archive, --symlinks and --explode together is still forbidden. 
When uploading a symlink to Artifactory, the symlink is represented in Artifactory as 0 size file with properties 
describing the symlink. This symlink representation is not yet supported by Artifactory when exploding symlinks from a zip.
> Archiving symlinks in upload command

- artifactory/commands/repository/repository.go
- artifactory/commands/repository/template.go
-----
Following [jfrog/jfrog-cli#1219](https://github.com/jfrog/jfrog-cli/issues/1219)
This commit adds support to the projectKey field in the repositories templates.
The `jfrog rt rpt` command will add the `<projectKey>-` prefix to the repository key if missing, to follow the requirement in Artifactory.
> Support projectKey in repo template

- artifactory/commands/distribution/createbundle.go
- artifactory/commands/distribution/updatebundle.go
-----
Release bundle `create` and `update` commands ignore the recursive flag.
From now on, if the `recursive` flag is missing in the FileSpec, or if a pattern is used, recursive=true will be used. The reason for the breaking change is to be consistent with the other commands.
> Bugfix - Release bundle recursive flag ignored

- artifactory/commands/npm/installorci.go
- utils/npm/version.go
-----
Fix npm getVersion() function.
Parse only version string without warning lines and improve error log.
> Fix npm version parsing command

- utils/mvn/utils.go
- utils/mvn/utils_test.go
-----
Validate that Maven version is  3.1.0 and above (released in 2013) before running maven commands.
following [1301 issue](https://github.com/jfrog/jfrog-cli/issues/1301)
> Add version validation for maven commands

- artifactory/commands/utils/configfile.go
- artifactory/commands/utils/configfile_test.go
- docs/common/helputils.go
- go.mod
- go.sum
- plugins/components/conversionlayer.go
- plugins/pluginmain.go
- plugins/signature.go
-----
Precondition for https://github.com/jfrog/jfrog-cli/pull/1328
Upgrade `codegangsta` to 1.22.5 in order to support fish autocompletion in the CLI, as provided by https://github.com/urfave/cli/pull/848.
`Codegansta` was renamed to `urfave`, and therefore I also changed the import paths to github.com/urfave/cli.
> Upgrade codegangsta CLI to 1.22.5

- xray/commands/audit/commonutils.go
-----
Fix audit command results table, following some issues with the `component` column that shows sub-root component instead of the root component on dependency trees with multi roots.
> Fix audit commands root component

- artifactory/commands/container/buildcreate.go
- artifactory/commands/container/pull.go
- artifactory/commands/container/push.go
- artifactory/commands/oc/startbuild.go
- artifactory/utils/container/buildinfo.go
- artifactory/utils/container/containermanager.go
- artifactory/utils/container/image.go
- artifactory/utils/container/image_test.go
- artifactory/utils/container/localagent.go
- artifactory/utils/container/manifest.go
- artifactory/utils/container/remoteagent.go
- go.mod
- go.sum
-----
*   Add support for collecting build-info for fat-manifest images.
*   Add support for [buildx](https://github.com/docker/buildx) in `build-docker-create` command.
[Buildx](https://github.com/docker/buildx) is a Docker CLI plugin for extended build capabilities with BuildKit. 
To collect build-info with buildx CLI, add [--metadata-file](https://github.com/docker/buildx/blob/master/docs/reference/buildx_build.md) flag to the buildx build command and a meta-data file will be generated at the end of the build. 
This file can be used with `build-docker-create` to collect build-info either for images or multi platform images.
Related PRs:
* https://github.com/jfrog/jfrog-cli/pull/1364
* https://github.com/jfrog/jfrog-client-go/pull/500
* https://github.com/jfrog/build-info-go/pull/27
> Add support for fat-manifest & buildx

- utils/coreutils/techutils.go
-----
According to the [official dotnet project samples ](https://github.com/dotnet/samples) we should consider a *.csproj file as an indicator for Nuget/Dotnet project.
> Add .csproj file as an indicator for NuGet/Dotnet technology

- artifactory/commands/npm/common.go
- artifactory/commands/npm/generic.go
- artifactory/commands/npm/installorci.go
-----
Running generic npm cmds such as `jf npm --version` should not look up for config file nor override local npmrc (used by `jf npm i/ci`).
> Remove any prerequisites for generic npm cmds

- general/project/projectinit.go
> Bugfix - Project init should print buildtools instructions before docker instructions

- artifactory/utils/utils.go
-----
An attempt to encrypt the password during `jf config add` command may fail for various reasons. Currently, we only print the HTTP code.
However, sometimes it would be helpful to print the response from Artifactory. For example:
> Log response after failure in encrypting password

- artifactory/utils/dotnet/solution/solution.go
-----
Resolves https://github.com/jfrog/jfrog-cli/issues/1463
In some cases, a dependency may not appear in the NuGet cache and the CLI returned the following message:
> The file C:\Users\username\.nuget\packages\microsoft.netcore.platforms\1.1.0\microsoft.netcore.platforms.1.1.0.nupkg doesn't exist in the NuGet cache directory but it does exist as a target in the assets files. Skipping adding this dependency to the build info. This might be because the package already exists in a different NuGet cache, possibly the SDK's NuGetFallbackFolder cache. Removing the package from this cache may resolve the issue.
The change introduced in https://github.com/jfrog/jfrog-cli-core/pull/303 didn't take this into consideration.
> Bugfix - Panic in Dotnet and NuGet commands

- artifactory/utils/dotnet/solution/solution.go
-----
Resolves https://github.com/jfrog/jfrog-cli/issues/1281#issuecomment-1068892650
Test: https://github.com/jfrog/jfrog-cli/pull/1482
In NuGet projects, a possible scenario is that project A contains project B as a project reference (like sub-module).
Currently, all dependencies of B appear in A. Furthermore - the RequestedBy field of these dependencies is nil because there is no way to traverse them from A.
This PR suggests removing the unreachable dependencies.
> Dependencies in NuGet subprojects are mixed

- artifactory/commands/utils/conditionaluploadutils.go
- utils/coreutils/tableutils.go
- utils/coreutils/tableutils_test.go
- utils/coreutils/utils.go
- utils/coreutils/utils_test.go
- xray/commands/audit/commonutils.go
- xray/commands/scan/buildscan.go
- xray/commands/scan/scan.go
- xray/utils/resultstable.go
- xray/utils/resultwriter.go
-----
The new format transforms the raw scan results into a "table like" json.
```
{
"Vulnerabilities": [],
"SecurityViolations": [],
"LicensesViolations": [],
"Licenses": []
}
```
Each table is an array of key:value objects, with the keys corresponding to the column names in the `table` format.
> New scan/audit pretty-json output format

- xray/utils/resultstable.go
The emoji will only be displayed if colored output is requested.
-----
> Separate emoji from severity title

- general/envsetup/envsetup.go
- utils/ioutils/ioutils.go
-----
When running a CLI command from a bash script (for example setup command) and trying to read a password from the console we get this error:"inappropriate ioctl for device".
> Fix: Scanning password from console fails when run from script

- go.mod
- go.sum
-----
Depends on: 
* https://github.com/jfrog/build-info-go/pull/85
* https://github.com/jfrog/jfrog-client-go/pull/594
* https://github.com/jfrog/jfrog-cli/pull/1552
> Duplicate build-info's artifacts are counted by their paths instead of their names

- artifactory/commands/transferconfig/transferconfig.go
-----
1. Getting the config-import version always returned 401.
2. Minor improvement of the log messages.
> TransferConfig: Fix 401 in target server verification

- xray/commands/offlineupdate/offlineupdate.go
- xray/commands/offlineupdate/offlineupdate_test.go
* Download the packages using CLI
* Maintain backward compatability to existing DBSync feature
(offlineupdates)
-----
> Add support for Xray's new DBSync V3 (offline updates) feature:

- artifactory/commands/transferconfig/transferconfig.go
- artifactory/commands/transferconfig/transferconfig_test.go
-----
Currently, the import shows lots of unnecessary data:
Let's make the verbosity of the import command optional:
> Add verbose flag in the TransferConfig command

- artifactory/commands/testdata/config_xmls_exclude_repos/cases/select-all.xml
- artifactory/commands/testdata/config_xmls_exclude_repos/input/artifactory.config.xml
- artifactory/commands/transferconfig/configxmlutils/includerepos_test.go
- artifactory/commands/transferconfig/transferconfig.go
- artifactory/commands/transferconfig/transferconfig_test.go
-----
Improved log in transfer-config command when the target repository is not empty.
Test parsing config descriptor with remote Go repository that includes VCS configuration.
> Improve error when target repo is not empty on transfer-config

- artifactory/commands/transferconfig/transferconfig.go
- artifactory/commands/transferconfig/transferconfig_test.go
-----
During the transfer config command, we don't need the metadata, since the hybrid migration import already excludes it by default.
Let's remove it from the export.
> Exclude metadata on config export

- artifactory/commands/repository/repository.go
- artifactory/commands/repository/template.go
-----
Fix this issue: https://github.com/jfrog/jfrog-cli-core/issues/330
Not possible to create a nuget local or remote repository with the "ForceNugetAuthentication" option enabled.
Approved in this PR: https://github.com/jfrog/jfrog-cli-core/pull/408
> Fix: Missing "ForceNugetAuthentication" in repository template

- common/commands/curl.go
- common/commands/curl_test.go
Reverts jfrog/jfrog-cli-core#435
Reverted because of unexpected breaking changes.
> Revert "Fix URI calculation on Xray and Artifcatory CURL commands."

- artifactory/commands/transferfiles/api.go
- artifactory/commands/transferfiles/filesdiff.go
- artifactory/commands/transferfiles/fulltransfer.go
- artifactory/commands/transferfiles/manager.go
- artifactory/commands/transferfiles/utils.go
- artifactory/utils/transfersettings_test.go
-----
Required for https://github.com/jfrog/jfrog-cli/pull/1632
To help with the integration tests in the jfrog-cli, expose the following variables:
* Rename aqlPaginationLimit -> AqlPaginationLimit 
* Rename getThreads() -> GetThreads
Add missing unit test of `transfersettings.go`.
> Expose transfer variables to allow testing

- artifactory/commands/transferfiles/transfer.go
- artifactory/commands/transferfiles/utils.go
- artifactory/commands/transferfiles/utils_test.go
-----
* Increase the number of stop attempts in graceful stopping to (5 X Artifactory nodes).
* Implement @eyalbe4 comments in https://github.com/jfrog/jfrog-cli-core/pull/452
> Transfer - Increase graceful-stop attempts

- artifactory/commands/testdata/config_xmls_exclude_repos/cases/select-all.xml
- artifactory/commands/testdata/config_xmls_exclude_repos/cases/select-local.xml
- artifactory/commands/testdata/config_xmls_exclude_repos/cases/select-one-from-all.xml
- artifactory/commands/testdata/config_xmls_exclude_repos/cases/select-release-bundle.xml
- artifactory/commands/testdata/config_xmls_exclude_repos/cases/select-remote.xml
- artifactory/commands/testdata/config_xmls_exclude_repos/input/artifactory.config.xml
- artifactory/commands/transferconfig/configxmlutils/includerepos.go
- artifactory/commands/transferconfig/configxmlutils/includerepos_test.go
- artifactory/commands/transferconfig/transferconfig.go
- artifactory/commands/transferfiles/transfer.go
- artifactory/commands/utils/configfile.go
- artifactory/utils/repositoryutils.go
- artifactory/utils/repositoryutils_test.go
-----
Depends on: https://github.com/jfrog/data-transfer/pull/24 and releasing of data-transfer 1.3.0.
Integration test: https://github.com/jfrog/jfrog-cli/pull/1635
* Support transferring and filtering of build-info repositories in transfer-config and transfer-files.
* Support creating and filtering release bundle repositories in transfer-config. **Transferring release bundle repositories files is not supported.**
> Transfer - support build-info and rb repositories

- artifactory/commands/transferconfig/transferconfig.go
-----
* Fail the transfer-config command if `[ERROR]` exists in the import logs.
* Add a hint to use the `--exclude-repos` flag.
Example:
> Config transfer - fail if errors found in the logs

- artifactory/commands/transfer/settings.go
- artifactory/commands/transferfiles/manager.go
- artifactory/commands/transferfiles/phase.go
- artifactory/commands/transferfiles/transfer.go
- artifactory/commands/transferfiles/utils.go
- artifactory/utils/transfersettings.go
-----
* Limit the number of transferring threads to 8 in build-info repositories.
* Add the limitation notice in the transfer-settings:
> Transfer - limit build info transferring threads

- artifactory/commands/transferconfig/transferconfig.go
- artifactory/commands/transferconfig/transferconfig_test.go
- go.mod
- go.sum
-----
Moved the default credentials check from jfrog-cli to jfrog-cli-core.
The default credentials check won't run if admin is locked. After the check, and only if admin doesn't have the default credentials, it will unlock admin to reset its failed login attempts counter in Artifactory and avoid him being suspended or locked.
> Fix login suspension in transfer-config

- artifactory/commands/transferfiles/state.go
- artifactory/commands/transferfiles/state_test.go
- artifactory/commands/transferfiles/transfer.go
-----
Added ignoreState flag to TransferFilesCommand. If true, the CLI will ignore the saved state of previous runs of the transfer.
> Transfer files ignoreState option

- artifactory/utils/storageinfo.go
-----
Get storage info should be running with 3 retries and a wait-interval of 1 second between each attempt.
> Transfer - fix storage info time between retries

- artifactory/commands/transferfiles/transferfileprogress.go
-----
If the progress bar was terminated after clicking ctrl+c, the phases slice will be empty.
This PR return nil if the phases slice is empty.
> Transfer - fix 'invalid phase id' message

- artifactory/commands/gradle/gradle.go
- artifactory/commands/mvn/mvn.go
- artifactory/utils/buildinfoproperties.go
- utils/gradle/utils.go
- utils/mvn/utils.go
- xray/audit/java/gradle.go
- xray/audit/java/mvn.go
-----
Whenever Maven/Gradle builds are run without a deployer, an error is returned:
As there are no deployed artifacts, the deployment view fails to calculate the deployed artifacts.
We fix this bug by first checking if there is a deployer before calculating the deployment view
> The Maven/Gradle build fails if there is no deployer in the config file

- artifactory/utils/projectconfig.go
Signed-off-by: sverdlov93 <sverdlov93@gmail.com>
-----
GetProjectConfFilePath() should return empty path if config not exist or error thrown
> Fix GetProjectConfFilePath return value

- artifactory/commands/transferfiles/srcpluginservice.go
- artifactory/commands/transferfiles/transfer.go
- artifactory/commands/transferfiles/transfer_test.go
- artifactory/commands/transferfiles/utils.go
-----
- Refactor and reduce number of lines in pollUploads function.
- Stop polling although there are still chunks in the deletedChunksSet, the nodes stop between phases will handle this case
- Fix bug in validateDataTransferPluginMinimumVersion
> Transfer Files - Improve polling when there is a network interrupt

- artifactory/commands/transferfiles/filesdiff.go
-----
Currently, If there are no errors in phase 1, the code initializes a producer-consumer, attempting to upload an empty list. This process takes 20 seconds for each repository.
This PR avoids handling errors in phase 2 if not needed.
> Transfer - skip handling errors if not needed

- artifactory/commands/transferfiles/api.go
- artifactory/commands/transferfiles/fulltransfer.go
- artifactory/commands/transferfiles/transfer_test.go
- artifactory/commands/transferfiles/utils.go
-----
Uploading empty build-info directories (without the .json files) is meaningless and may cause unexpected behavior. One example of such unexpected behavior is the following error: (notice that the "name" is empty")
```CSV
Repo,Path,Name,Status,StatusCode,Reason,Time
artifactory-build-info,build-name,,FAIL,500,"FileExpectedException: Expected a file but found a folder, at: artifactory-build-info:build-name",2022-09-01T18:56:45Z
```
> Transfer - Avoid uploading empty build-info dirs

- artifactory/commands/testdata/config_xmls_federated_repos/expected/artifactory.config-0.xml
- artifactory/commands/testdata/config_xmls_federated_repos/expected/artifactory.config-1.xml
- artifactory/commands/testdata/config_xmls_federated_repos/expected/artifactory.config-2.xml
- artifactory/commands/testdata/config_xmls_federated_repos/expected/artifactory.config-3.xml
- artifactory/commands/transferconfig/configxmlutils/federatedrepos.go
- artifactory/commands/transferconfig/configxmlutils/fereratedrepos_test.go
- artifactory/commands/transferconfig/transferconfig.go
-----
Remove all federated members from all federated repositories. The reason for that change is to allow importing configuration from non-accessible members' URLs.
Add "Your Federated repositories have been transferred to your target instance, but their members have been removed on the target" message in the end:
> Transfer config - remove all federated members

- common/commands/config.go
- common/commands/config_test.go
-----
Warn when a user configures an HTTP connection to the platform:
Interactive:
Non-interactive:
> Warn when configuring unsafe HTTP connections

- artifactory/commands/dotnet/dotnetcommand.go
- artifactory/commands/dotnet/dotnetcommand_test.go
- artifactory/commands/dotnet/dotnetcorecli.go
- artifactory/commands/dotnet/nuget.go
- go.mod
- go.sum
-----
Following https://github.com/jfrog/jfrog-cli/issues/1623.
The configfile flag was not passed correctly to the Dotnet module when it was generated.
Breaking change: Removed unused setter `SetUseNugetAddSource`
Depends on https://github.com/jfrog/build-info-go/pull/103.
> Fix Dotnet configfile usage

- artifactory/commands/transferfiles/delayedartifactshandler.go
- artifactory/commands/transferfiles/filesdiff.go
- artifactory/commands/transferfiles/fulltransfer.go
- artifactory/commands/transferfiles/manager.go
- artifactory/commands/transferfiles/utils.go
-----
Bug fix - changing threads did not update both producer consumers.
Bug fix - panic could occur if writers are closed before producer consumers.
> Transfer - producer consumers fixes

- artifactory/commands/transferfiles/api.go
- artifactory/commands/transferfiles/fulltransfer.go
- artifactory/commands/transferfiles/phase.go
- artifactory/commands/transferfiles/propertiesdiff.go
- artifactory/commands/transferfiles/srcpluginservice.go
- artifactory/commands/transferfiles/transfer.go
- artifactory/commands/transferfiles/transfer_test.go
- artifactory/commands/transferfiles/utils.go
-----
Depends on https://github.com/jfrog/data-transfer/pull/37
* Add support for an HTTP proxy, configured in the platform UI.
* Check connectivity between the source and the target Artifactory servers before starting the transfer.
> Transfer - Support HTTP proxy and check connectivity

- artifactory/utils/storageinfo.go
- artifactory/utils/storageinfo_test.go
> Bug fix - GetReposTotalSize was missing reset between polling

- artifactory/commands/transferfiles/utils.go
- artifactory/commands/transferfiles/utils_test.go
-----
When transferring files between local or federated repositories, we update the max unique snapshots in Maven, Gradle, Docker, NuGet, ivy, Sbt, and Docker repositories to 0.
Setting the max snapshots on federated repositories creates a REST for a local repository type instead of a federated repository type. As a result, we get the following error:
> 19:15:34 [🚨Error] server response: 404 Not Found
```json
{
"errors": [
{
"status": 404,
"message": "No repository maven-federated was found."
}
]
}
```
> Transfer files - fix max snapshots on fede repos

- artifactory/commands/transferfiles/utils.go
-----
* Avoid printing `error returned when getting upload chunks statuses: context canceled`
* Avoid adding "context canceled" errors to the CSV error file
> Transfer files - Better handling context canceled

- artifactory/commands/transferfiles/filesdiff.go
- artifactory/commands/transferfiles/fileserror.go
- artifactory/commands/transferfiles/fulltransfer.go
- artifactory/commands/transferfiles/manager.go
- artifactory/commands/transferfiles/phase.go
- artifactory/commands/transferfiles/utils.go
-----
When attempting to stop the transfer-files command with CTRL+C the command doesn't stop. This is caused as a result of the new `notifyIfBuilderFinished ` and `notifyIfUploaderFinished ` mechanisms, which may cause the application to wait for the two producer-consumers to finish, even if the system is in "shut down more". 
To fix the issue, these two mechanism are now released as part of the `ShouldStop` function.
See the these lines which trigger the release. They receive a new "force" boolean set to true.
```
phase.pcDetails.notifyIfBuilderFinished(true)
phase.pcDetails.notifyIfUploaderFinished(true)
```
> Transfer - CTRL+C doesn't shut down the process

- artifactory/commands/transferfiles/filesdiff.go
- artifactory/commands/transferfiles/fileserror.go
- artifactory/commands/transferfiles/fulltransfer.go
- artifactory/commands/transferfiles/manager.go
- artifactory/commands/transferfiles/phase.go
- artifactory/commands/transferfiles/phase_test.go
- artifactory/commands/transferfiles/utils.go
-----
Followup https://github.com/jfrog/jfrog-cli-core/pull/570
Notify and cancel producer-consumers after every step - full transfer, diff, or file errors transfer. This expected to happen before calling to ShouldStop, right after clicking ctrl+c.
> Transfer - Notify pc finished after graceful stop

- artifactory/commands/transferfiles/state/state.go
- artifactory/commands/transferfiles/status_test.go
- utils/tests/utils.go
-----
Followup https://github.com/jfrog/jfrog-cli-core/pull/581
* Fix the following unreleased issue: When the repository does not exist in the state, SetRepoState does not initialize appropriately the repository's total size and total files.
* Add unit tests to the `transfer-files --status` option.
* Move RedirectLogOutputToBuffer from https://github.com/jfrog/jfrog-cli/blob/v2.27.1/utils/tests/utils.go#L672 to the core.
> Fix minor issue in state and add tests

- artifactory/commands/transferfiles/transfer.go
-----
Avoid the following error, when the value of `UsedSpaceInBytes` cannot be retrieved from Artifactory.
```
strconv.ParseInt: parsing "": invalid syntax
```
> Transfer - Overcome empty usedSpaceInBytes

- artifactory/commands/transferfiles/transfer.go
- artifactory/utils/storageinfo.go
- artifactory/utils/storageinfo_test.go
-----
Followup: https://github.com/jfrog/jfrog-cli-core/pull/590
UsedSpaceInBytes does not exist in the repository summary in Artifactory 6. In storageinfo.go we fallback to using the UsedSpace field. 
This PR makes the code in transfer.go to use the fallback too.
> Transfer - Better parsing of repository used space

- artifactory/utils/storageinfo.go
- artifactory/utils/storageinfo_test.go
-----
Fix the following error received in transfer-files:
> strconv.ParseFloat: parsing "1,004.64": invalid syntax
> Fix parsing error when parsing storage size

- artifactory/commands/transferfiles/status.go
-----
Fixes the "Estimated time remaining:" layout of the `jf rt transfer-files --status` view, which is currently - 
to be -
> [Unreleased bug] Transfer - Fix "status" view layout

- artifactory/commands/transferfiles/filesdiff.go
-----
The following illegal AQL query may be created as part of Phase 2, if no results are founds.
```
16:37:24 [Error] server response: 400 Bad Request
Failed to parse query: items.find({"$or":[]}).include("name","repo","path","actual_md5","actual_sha1","sha256","size","type","modified","created","property"), it looks like there is syntax error near the following sub-query: ]}).include("name","repo","path","actual_md5","actual_sha1","sha256","size","type","modified","created","property")
```
> Transfer - Illegal AQL query may be sent in Phase 2

- artifactory/commands/transferfiles/state/statemanager.go
-----
**Fix the following issue**:
1. User runs transfer-files
2. User interrupts the transfer by clicking on ctrl+c
3. User run transfer-files again
**Results**:
The `Storage` and `Files` count is the sum of all previous transfer-files runnings and we see this after running transfer-files with the --status flag.
> Transfer - wrong storage and files count in status

- artifactory/commands/transferfiles/filesdiff.go
- artifactory/commands/transferfiles/manager.go
- artifactory/commands/transferfiles/transferfileprogress.go
-----
Fix unreleased bug caused Nil Pointer Dereference in CI mode and in the integration tests in the JFrog CLI.
In CI mode, the transfer progress bar is nil and therefore we should check for nil before updating the progress bar.
Steps to reproduce:
Run the following command:
```
CI=true ./jf rt transfer-files source-server target-server
```
Results:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x18c9aeb]
goroutine 125 [running]:
github.com/jfrog/jfrog-cli-core/v2/artifactory/commands/transferfiles.(*TransferProgressMng).increaseTotalSize(...)
/Users/yahavi/code/cli/jfrog-cli-core/artifactory/commands/transferfiles/transferfileprogress.go:269 …
```
> Transfer - fix NPD in CI mode

- artifactory/commands/transferfiles/fulltransfer.go
-----
Fix the following issue when running `jf rt transfer-files` on Artifactory 6:
```
[🚨Error] strconv.ParseInt: parsing "": invalid syntax
```
> Transfer files - fix parsing error in progress bar

- artifactory/utils/buildutils.go
- artifactory/utils/buildutils_test.go
-----
A JFrog CLI command searches for the config file at the PWD file path. The PR adds logic to handle permission denials gracefully.
> Searching JFrog config shouldn't return a permission denied error

- common/commands/config.go
- go.mod
- go.sum
-----
Add subject to access tokens in `jf c show` command. The subject can be extracted only in JWT access tokens. In reference tokens, for example, the subject is impossible to extract.
> Show JWT token subject in 'jf c show'

- artifactory/utils/buildutils.go
-----
Following the changes made by https://github.com/jfrog/jfrog-cli-core/pull/668, In this PR, the log level is lowered from info to debug. A reporter of this issue noted that debugging an issue could result in confusion.
> Change the log level while searching for the build name

- artifactory/commands/utils/result.go
-----
When there are no deployable artifacts in Maven and Gradle, the deployable artifacts file is empty.
In this case, we may want to exit gracefully. However this error is returned:
> panic: unexpected end of JSON input
goroutine 1 [running]:
github.com/jfrog/jfrog-cli-core/v2/utils/coreutils.PanicOnError({0x100e331e0?, 0xc000012060?})
github.com/jfrog/jfrog-cli-core/v2@v2.29.3/utils/coreutils/utils.go:101 +0x3a
github.com/jfrog/jfrog-cli-core/v2/artifactory/commands/utils.unmarshalDeployableArtifactsJson({0xc000498420?, 0xc000515408?})
github.com/jfrog/jfrog-cli-core/v2@v2.29.3/artifactory/commands/utils/result.go:148 +0x137
> Unexpected error when there are no deployable artifacts

- artifactory/commands/transferfiles/transfer.go
-----
If the Transfer user plugin was not installed / not installed correctly we will give more information to point the user to the installation instructions, the error will be shown as followed:
> Transfer - If plugin not install log information

- artifactory/utils/container/buildinfo.go
- artifactory/utils/container/buildinfo_test.go
- artifactory/utils/container/localagent.go
-----
The build-info collection may fail if some or all of the image is not found in Artifactory after the image was pulled.
Clients may end up pulling images from their local cache rather than downloading them from Artifactory.
> Docker - Skip build-info if there are no image layers in Artifactory

- .github/workflows/analysis.yml
- .github/workflows/frogbot-scan-and-fix.yml
- .github/workflows/frogbot-scan-pr.yml
- .github/workflows/test.yml
- go.mod
> Upgrade go version in go.mod to 1.20

- .github/workflows/test.yml
- artifactory/commands/buildinfo/addgit.go
- artifactory/commands/generic/download.go
- artifactory/commands/golang/archive.go
- artifactory/commands/utils/remoteurlchecker.go
- go.mod
- go.sum
- plugins/components/conversionlayer.go
- xray/audit/java/gradle.go
- xray/audit/java/javautils.go
- xray/audit/java/mvn.go
> Fix lint issues found

- xray/audit/java/mvn.go
-----
The Maven Enforcer and the Maven Checkstyle plugin are not necessary for the dependency tree. Let's disable them.
> Disable Enforcer and Checkstyle in Maven audit

- xray/audit/npm/npm.go
- xray/audit/npm/npm_test.go
- xray/commands/testdata/npm-scripts/package.json
-----
Add the `--ignore-scripts` flag to prevent the execution of scripts before/after `npm install`.
> Add ignore-scripts flag to npm audit

- artifactory/commands/transferconfig/transferconfig.go
-----
Fix insufficient export dir permissions that occurred in RedHat.
> Transfer config - insufficient export dir permissions

- xray/commands/audit/generic/generic.go
- xray/utils/resultwriter.go
-----
This PR introduces the following changes:
- The contextual analysis logic will run only if the user is entitled to advance security. (instead of throwing an error).
- Display a clear message if the user is not entitled.
> Adjust `Contextual Analysis` run conditions message

- artifactory/utils/dependenciesutils.go
- artifactory/utils/dependenciesutils_test.go
-----
Fix the following issue when running Maven or audit command using the `JFROG_CLI_RELEASES_REPO` environment variable:
> 05:43:21 [Info] Downloading JFrog's Dependency from  https://acme.jfrog.io/artifactory/jcenter-virtual/org/jfrog/buildinfo/build-info-extractor-maven3/2.40.0/build-info-extractor-maven3-2.40.0-uber.jar
05:43:21 [Warn] Failed to get remote file details.
Got: server response: 401 
05:43:21 [Error] 401  received when attempting to download https://acme.jfrog.io/artifactory/jcenter-virtual/org/jfrog/buildinfo/build-info-extractor-maven3/2.40.0/build-info-extractor-maven3-2.40.0-uber.jar
> Missing auth details while downloading an extractor

- xray/commands/audit/applicabilitymanager.go
- xray/commands/audit/applicabilitymanager_test.go
-----
This PR includes the following:
* old logic: If xray scan results don't contain direct dependencies -> don't present contextual analysis column in output
* new logic: If xray scan results don't contain direct dependencies && user is entitled for JAS -> present contextual analysis column in output
> Contextual Analysis Column appearance update

- artifactory/commands/transferfiles/transfer.go
-----
This pull request designates certain types of errors as unrecoverable due to the potential risk of data loss without proper reporting. The specified errors that are considered unrecoverable include:
* Transfer action error: Occurs when there is an error in AQL (Artifactory Query Language) or cache retrieval.
* Errors channel error: Refers to errors encountered while writing to the error files.
* Delayed artifact manager error: Indicates errors that arise when writing to the delayed artifacts files.
* Execution error: Relates to errors within the producer-consumer mechanism.
* Interruption error: Occurs when the user interrupts the transfer process by pressing Ctrl+C or running jf rt transfer-files --stop.
By identifying these errors as unrecoverable, the pull request aims to ensure …
> Transfer - exit on unrecoverable errors

- artifactory/commands/transferfiles/fulltransfer.go
-----
The transfer files command utilizes an AQL to retrieve pages of 10,000 files within a repository directory. We determine that it is the last page when the AQL results are less than 10,000.
The introduction of the locally generated filter in the pull request at https://github.com/jfrog/jfrog-cli-core/pull/751 modifies this behavior. In certain package types, such as npm, certain items are filtered out, resulting in a decrease in the number of search results. Consequently, this decrease in search results from 10,000 may erroneously indicate that we are on the last page.
This pull request resolves the issue by implementing a fix that addresses the problem. The fix involves counting the size of the search results before applying any filtering. By doing so, the issue of incorrectly …
> Transfer - Missing files in large repositories

- xray/commands/audit/generic/generic.go
- xray/commands/scan/buildscan.go
- xray/commands/scan/scan.go
- xray/utils/resultwriter.go
* Fixes https://github.com/jfrog/jfrog-cli/issues/2012
* Improve the appearance of the messages shown at the top of the `jf audit`, `jf scan` and `jf docker scan` results table.
> `jf audit` generates invalid JSON format 

- artifactory/commands/repository/template.go
- artifactory/commands/transferfiles/delayedartifactshandler.go
- general/cisetup/utils.go
- utils/progressbar/progressbarmng.go
-----
This PR introduces the following changes:
1. Fixes a minor bug regarding gradle cases in some switch cases. (The `go` default switch behavior **is not** to fall through cases. To achieve that, the ',' notation or the keywords `fallthrough` is necessary)
2.  Replace the fallthrough with the ',' notation for better readability .
3.  Remove the `filterColor` that I believe was not used.
> Fix switch statements and cleanup code

- artifactory/commands/transferfiles/localgeneratedfilter.go
- artifactory/commands/transferfiles/localgeneratedfilter_test.go
- artifactory/commands/transferfiles/phase.go
- artifactory/commands/transferfiles/transfer.go
-----
JFrog CLI tests: https://github.com/jfrog/jfrog-cli/pull/2018
Limit the number of concurrent 'POST /localgenerated/filter/paths' requests to 2, to reduce the load on the target server.
> Transfer - Limit local generated filter requests

- artifactory/commands/transferfiles/fulltransfer.go
-----
Setting properties directly on the repository itself doesn't serve any practical purpose. Additionally, replication involves setting properties on a repository, which we would like to avoid transferring to the target.
> Transfer - Exclude transferring the repository props

- artifactory/commands/transferfiles/filesdiff.go
-----
Same as https://github.com/jfrog/jfrog-cli-core/pull/815, but for phase 2.
Diffs that span 15 minutes and include over 10,000 files may incorrectly indicate the last page if there are locally generated files in the mix. As a result, items beyond the 10,000th file may be skipped.
> Transfer - Missing diffs in large diffs

- artifactory/commands/transferfiles/filediff_test.go
- artifactory/commands/transferfiles/filesdiff.go
-----
Fix the following error happens in the phase 2 of the transfer-files command:
> unexpected error occurred during upload
org.artifactory.api.repo.exception.FileExpectedException: Expected a file but found a folder, at: repo-name:path/in/repo/dir-name
In the Diffs phase (phase 2), the JFrog CLI treats all items as files and uses the folder name as the file name. However, the Data Transfer plugin expects an empty "name" field when the item is a folder.
> Transfer - Empty dirs are not transferred in diffs

- artifactory/commands/transferfiles/manager.go
- artifactory/commands/transferfiles/state/runstatus.go
- artifactory/commands/transferfiles/state/statemanager.go
- artifactory/commands/transferfiles/state/timeestimation.go
- artifactory/commands/transferfiles/state/utils.go
- artifactory/commands/transferfiles/state/utils_test.go
- artifactory/commands/transferfiles/status.go
- artifactory/commands/transferfiles/status_test.go
- artifactory/commands/transferfiles/utils.go
- artifactory/commands/transferfiles/utils_test.go
-----
Save in the TransferRunStatus the chunks that have been in transit for more than 30 minutes.
This allows them to be displayed running `jf rt transfer-files --status`.
> Transfer - Show stale chunks in --status

- artifactory/commands/transferconfig/transferconfig.go
- artifactory/commands/utils/transferconfigbase.go
- artifactory/commands/utils/transferconfigbase_test.go
-----
To prevent data loss when executing the `jf rt transfer-config` command twice, this pull request suggests modifying the command to make it skip the process of deleting and recreating existing repositories on the target server.
If a repository import is skipped, the following message will be displayed:
> 10:11:57 [🔵Info] Repository 'conda-local' already exists in the target Artifactory server. Skipping.
10:11:57 [🔵Info] Repository 'conda-remote' already exists in the target Artifactory server. Skipping.
10:11:57 [🔵Info] Repository 'conda' already exists in the target Artifactory server. Skipping.
> Transfer config - Avoid deleting existing repos

- utils/coreutils/tableutils.go
- xray/commands/curation/audit.go
- xray/commands/curation/audit_test.go
> Add support for multiple policy in on block event

- xray/audit/java/gradle.go
- xray/audit/java/gradle_test.go
- xray/audit/java/javautils.go
- xray/audit/java/mvn.go
- xray/audit/java/mvn_test.go
- xray/commands/audit/generic/auditmanager.go
- xray/utils/models.go
-----
* Remove the 'releases' repository fields and their usage when they are not derived from the 'JFROG_CLI_RELEASES_REPO' environment variable.
> Audit - remove redundant releases remote repo code

- go.mod
- go.sum
> Align dev branch with master

- xray/audit/jas/secretsscanner.go
-----
The scanner names param is used to determine which secrets scanners should run when a secrets detection is performed. 
In our use case, enabling the run of all scanners is better than maintaining this list.
> Secrets scanners - Enable all scanners

- artifactory/commands/transferfiles/fulltransfer.go
- artifactory/commands/transferfiles/state/state_test.go
- utils/reposnapshot/node.go
- utils/reposnapshot/snapshotmanager_test.go
-----
This fix resolves an issue with the` jf rt transfer-files` command.
The symptom of this issue is the following error message that occasionally could be seen in the log:
repo snapshot manager - could not reach the representing node for path...
The key to fixing the issue is the change made to the findMatchingNode function. The issue was that the findMatchingNode function could not always return the node. This is because the node may not be in the snapshot cache. It may yet to be discovered, or maybe it was discovered, but the snapshot cache didn't get a chance to get persisted yet, because of a shutdown of the command.
With this fix, the findMatchingNode function always fetches the node, It returns it if it's cached, creates it, and adds it to the cache if it isn't cached.
> Transfer files - Fix repo snapshot manager error

- xray/commands/curation/audit.go
- xray/commands/curation/audit_test.go
> Fix duplicate rows and added scope for component name

- artifactory/commands/transferconfig/transferconfig.go
- artifactory/commands/transferconfig/transferconfig_test.go
- artifactory/commands/transferconfigmerge/transferconfigmerge.go
- artifactory/commands/utils/transferconfigbase.go
- artifactory/commands/utils/transferconfigbase_test.go
- common/tests/utils.go
-----
Fix the following problem in `transfer-config` and `transfer-config-merge` commands:
```
09:24:39 [Debug] Sending HTTP PUT request to: https://acme.jfrog.io/artifactory/api/repositories/repo-name
09:24:39 [🚨Error] server response: 400 
{
"errors": [
{
"status": 400,
"message": "The repository key 'repo-name' should start with the project key and a dash: 'proj-'\n"
}
]
}
```
**Algorithm**
For each repository, prior to its creation in the target location, follow these steps:
If the repository is linked to a project and its name doesn't commence with the project key prefix, perform the subsequent REST operations:
1. `DELETE https://acme.jfrog.io/access/api/v1/projects/_/attach/repositories/repo-name` - Delete the metadata in Access.
2. `PUT …
> Transfer config - Issue in repos assigned to projects

- utils/coreutils/techutils.go
- xray/commands/audit/generic/auditmanager.go
- xray/commands/utils/utils.go
> Improve Audit command technology detection

- common/commands/config.go
- common/commands/config_test.go
-----
Following https://github.com/jfrog/jfrog-cli/issues/2153 that was introduced in https://github.com/jfrog/jfrog-cli-core/pull/904
> Fix non-interactive config without providing server ID

- xray/commands/audit/jasrunner.go
- xray/utils/analyzermanager.go
- xray/utils/resultwriter.go
-----
Use JFROG_CLI_ANALYZER_MANAGER_VERSION to set analyzer manager version
> Set analyzer manager version by environment variable 

- xray/utils/analyzermanager.go
> Fix panic in Analyzer Manager execution

- artifactory/utils/dependenciesutils.go
- utils/usage/usage.go
- utils/usage/usage_test.go
> Don't send Xray usage until available for all users

- go.mod
- go.sum
- xray/commands/audit/jas/applicability/applicabilitymanager.go
- xray/commands/audit/jas/applicability/applicabilitymanager_test.go
- xray/commands/audit/jas/common.go
- xray/commands/audit/jas/commons_test.go
- xray/commands/audit/jas/iac/iacscanner.go
- xray/commands/audit/jas/iac/iacscanner_test.go
- xray/commands/audit/jas/sast/sastscanner.go
- xray/commands/audit/jas/sast/sastscanner_test.go
- xray/commands/audit/jas/secrets/secretsscanner.go
- xray/commands/audit/jas/secrets/secretsscanner_test.go
- xray/commands/audit/jas/testdata/.jfrog/jfrog-apps-config.yml
- xray/utils/analyzermanager.go
-----
Support the new `.jfrog/jfrog-apps-config.yml` file to allow configuring JFrog Advanced Security scanners.
https://github.com/jfrog/jfrog-apps-config
Integration test: https://github.com/jfrog/jfrog-cli/pull/2199
> Support JFrog Apps Config file

- utils/usage/usage.go
- utils/usage/usage_test.go
> Report Usage - Improve Errors Messages

- artifactory/commands/transferfiles/longpropertycheck.go
- artifactory/commands/transferfiles/utils.go
- artifactory/utils/storageinfo.go
- artifactory/utils/utils.go
- go.mod
- go.sum
-----
Incorporate a 1-minute timeout for all HTTP requests made to the Data Transfer plugin (source plugin) within the `jf rt transfer-files` command.
> Transfer - Add 1 minute timeout to all requests

- artifactory/commands/transferfiles/phase.go
- go.mod
- go.sum
-----
Depends on https://github.com/jfrog/gofrog/pull/40
Improve the graceful stop mechanism (`ctrl+c` or `--stop`) by stop executing pending tasks.
> Transfer - Improve the graceful stop mechanism

- artifactory/commands/transferfiles/delayedartifactshandler.go
- artifactory/commands/transferfiles/delayedartifactshandler_test.go
- artifactory/commands/transferfiles/fileserror.go
- artifactory/commands/transferfiles/status.go
- artifactory/commands/transferfiles/status_test.go
- utils/progressbar/transferprogressbarmanager.go
-----
Currently, no one is calling SetTotalSizeAndFilesPhase3. This caused the progress bar to be empty in phase 3.
Before:
After:
> Transfer - Fix phase 3 progressbar

- utils/progressbar/progressbarmng.go
- utils/progressbar/transferprogressbarmanager.go
This reverts commit 9b64c74d7c9426c8b610e05c8655dd515a7a22d3.
-----
* Revert most of #997 changes because I figured out that the progress that didn't get filled is actually expected:
Total files: 103
Delayed files: 34
Errors: 1
103 - 34 - 1 = 68.
* Keep the phase 3 label fix
> Transfer - Progress should only represent successful storage transfer

- artifactory/commands/transferfiles/delayedartifactshandler.go
-----
Fix the following panic:
```
05:22:01 [Info] ========== Running 'Full Transfer Phase' for repo 'docker-local-big'... ==========
panic: close of closed channel
goroutine 280 [running]:
github.com/jfrog/jfrog-client-go/utils/io/content.(*ContentWriter).Close(0xc011ab7180)
/Users/yahavi/code/cli/jfrog-client-go/utils/io/content/contentwriter.go:167 +0x37
github.com/jfrog/jfrog-cli-core/v2/artifactory/commands/transferfiles.(*SplitContentWriter).closeCurrentFile(0xc0002183f0)
/Users/yahavi/code/cli/jfrog-cli-core/artifactory/commands/transferfiles/delayedartifactshandler.go:367 +0x45
github.com/jfrog/jfrog-cli-core/v2/artifactory/commands/transferfiles.(*SplitContentWriter).close(...)
/Users/yahavi/code/cli/jfrog-cli-core/artifactory/commands/transferfiles/delayedartifactshandler.go:392 …
```
> Transfer - Fix "close of closed channel" panic

- utils/reposnapshot/node.go
-----
In the given situation, a deadlock could potentially arise. Let's look at the nodes A, B, and C:
**Thread 1:**
convertToWrapper -> `acquired lock on A` -> convertToWrapper -> `acquired lock on B` -> convertToWrapper -> `Attempt to acquire lock on C`
**Thread 2:**
CheckCompleted -> setCompleted -> `acquired lock on C` -> CheckCompleted -> setCompleted -> `Attempt to acquire lock on B`
Both Thread 1 and Thread 2 find themselves in a state of mutual waiting. Thread 1 is waiting for the mutex of C, which is held by Thread 2, while Thread 2 is waiting for the mutex of B, which is held by Thread 1.
The solution is to ensure that each thread never holds more than one mutex at a time.
Proof for thread 1's scenario:
```
goroutine 299 [sync.Mutex.Lock, 680 minutes]:
runtime.gopark(0xfca5e0?, …
```
> Transfer - Remove recursive locks in snapshot node

- artifactory/commands/transferfiles/manager.go
- artifactory/commands/transferfiles/phase.go
- artifactory/commands/transferfiles/phase_test.go
- artifactory/commands/transferfiles/utils.go
-----
Fix 2 issues in the Graceful Stop mechanism of `jf rt transfer-files` command:
1. Create producerConsumerWrapper pointer in createTransferPhase to allow access it in StopGracefully:
```go
func (pb *phaseBase) StopGracefully() {
if pb.progressBar != nil {
pb.progressBar.StopGracefully()
}
if pb.pcDetails != nil { // <- Was always nil
pb.pcDetails.chunkBuilderProducerConsumer.Cancel(true)
pb.pcDetails.chunkUploaderProducerConsumer.Cancel(true)
}
}
```
2. Since the Graceful stop mechanism is async and we poll interruptIfRequested every 20 seconds, there is a chance that more than 1 interruption signal will be sent to the "stopSignal" channel. This will cause the code to freeze.
> Transfer - Graceful stop does not stop immediately

- artifactory/commands/transferfiles/localgeneratedfilter.go
-----
Increase the max number of `/api/localgenerated` REST in parallel to 5. Without this change, we see that the number of running threads can't go above 30 in Docker repositories.
> Transfer - Increase locally generated concurrency

- artifactory/utils/projectconfig.go
- go.mod
- go.sum
- xray/commands/audit/auditparams.go
- xray/commands/audit/sca/npm/npm.go
- xray/commands/audit/sca/npm/npm_test.go
- xray/commands/audit/scarunner.go
- xray/utils/auditbasicparams.go
-----
Summary of Changes:
Automatically collects and inserts details of the Artifactory server and resolve repository into Audit parameters (for future use in dependency tree construction). This adjustment applies to all flows that construct a dependency tree.
Enhances the building of NPM dependency trees to resolve dependencies from an Artifactory server when configured by the user.
Introduces new parameters within Audit parameters to allow users to provide customized installation commands for building dependency trees. Note that not all entry points support the provision of these parameters.
Depends on: https://github.com/jfrog/build-info-go/pull/207
> Enhancements to Artifactory Integration and NPM dependency tree building

- artifactory/commands/transferfiles/delayedartifactshandler.go
- artifactory/commands/transferfiles/fileserror.go
- artifactory/commands/transferfiles/utils.go
-----
Halting the "transfer-files" process while delayed artifacts are being transferred might result in the early removal of the delayed artifacts file before all the chunks are properly uploaded. As a result, these files won't be uploaded unless you employ the `--ignore-state` flag. A similar problem can occur during the handling of error files.
This image serves as an illustration of the problem:
> Transfer - Interruption may causes data loss

- xray/utils/resultwriter.go
- xray/utils/resultwriter_test.go
-----
* Fixes Github integration validation
_**Before:**_
```
{
"ruleId": "CVE-2023-5363_debian:bookworm:openssl_3.0.11-1~deb12u1",
"ruleIndex": 43,
"level": "none",
"message": {
"text": "[CVE-2023-5363] sha256__6cd9f01fb9e511a9e611c6592d62412c0fead4b2b09dc3de7fbf6b50a8df0eed.tar"
}
}
```
_**After:**_
```
{
"ruleId": "CVE-2023-5363_debian:bookworm:openssl_3.0.11-1~deb12u1",
"ruleIndex": 43,
"level": "none",
"message": {
"text": "[CVE-2023-5363] sha256__6cd9f01fb9e511a9e611c6592d62412c0fead4b2b09dc3de7fbf6b50a8df0eed.tar"
},
"locations": [
{
"physicalLocation": {
"artifactLocation": {
"uri": "Package Descriptor"
}
}
}
]
}
```
> Xray SCA scan - always show results with location on Sarif output

- utils/coreutils/techutils.go
-----
- The build.gradle/build.gradle.kts file is generally mandatory for Gradle projects. The build.gradle file is where you define the configuration for your project, including dependencies, plugins, tasks, and other build-related settings. 
- This is why it serves as a sufficient indicator that a directory represents a Gradle project.
> Refine gradle projects indicators

- xray/commands/audit/jas/common.go
-----
Followup https://github.com/jfrog/jfrog-cli-core/pull/1022
* `.git` should be excluded in JAS too
* In Maven, the target directory should be exactly "target"
> Tweak JAS exclude patterns

- xray/utils/resultwriter.go
- xray/utils/resultwriter_test.go
-----
Remove space character from the value of the default descriptor for SCA scan results.
This issue causes:
```
Error: Code Scanning could not process the submitted SARIF file:
an invalid URI was provided as a SARIF location: parse "file://Package Descriptor": invalid character " " in host name
```
> SCA scan - Remove space in default descriptor

- xray/utils/resultstable.go
- xray/utils/resultwriter.go
- xray/utils/resultwriter_test.go
-----
* Improve Audit by allowing to specify license violations with locations in Sarif format (default), this way license violations can be uploaded to places that allows only results with location (like Github), prerequisite for https://github.com/jfrog/frogbot/pull/575.
* Allow to specify `allowedLicenses` instead of `watch` to get a license violations
* Fix bug where `summary` field was not populated for `violations` in simple json
> Audit - Sarif output, show default location for license violation

- go.mod
- go.sum
-----
On CircleCI when updating `go-pretty` from `v6.4.0` to `v6.4.1`+ the content of our tables is empty
as described here:
https://github.com/jfrog/jfrog-cli/issues/1858
opened an issue to investigate and try to fix this:
https://github.com/jedib0t/go-pretty/issues/285
> Downgrade the go-pretty dependency due to a bug

- artifactory/commands/transferfiles/state/runstatus.go
- artifactory/commands/transferfiles/state/statemanager.go
- artifactory/commands/transferfiles/state/statemanager_test.go
- artifactory/commands/transferfiles/state/timeestimation.go
- artifactory/commands/transferfiles/state/timeestimation_test.go
- artifactory/commands/transferfiles/status.go
- artifactory/commands/transferfiles/status_test.go
- artifactory/commands/transferfiles/transfer.go
- utils/progressbar/transferprogressbarmanager.go
-----
Introduce a new time estimation algorithm for the `jf rt transfer-files` command:
**Divide the transferred bytes in the ongoing process by the remaining size.**
The time estimation will only show up if these conditions are fulfilled:
1. Five minutes have elapsed since the transfer started.
2. A minimum of one file has been successfully transferred.
3. The calculated speed is at least one byte per second.
> Transfer - Improve time estimation algorithm

- artifactory/commands/transferfiles/filesdiff.go
- artifactory/commands/transferfiles/fulltransfer.go
- artifactory/commands/transferfiles/longpropertycheck.go
- artifactory/commands/transferfiles/longpropertycheck_test.go
- artifactory/commands/transferfiles/transfer.go
- artifactory/commands/transferfiles/utils.go
- artifactory/commands/utils/precheckrunner/remoteurlchecker.go
-----
Enhance and refine the long properties check that occurs after executing `jf rt transfer-files <source> <target> --precheck`:
* Extend the timeout period from 1 minute to 30 minutes.
* Utilize `.distinct(false)` whenever feasible.
> Transfer - Fix and improve long props check

- xray/commands/audit/jas/applicability/applicabilitymanager.go
-----
- The applicability scanner returns an error when parsing a configuration file without CVEs.
- This pull request adds a condition to execute the applicability scanner only if any CVEs were found during the SCA scan.
> Update conditions for running contextual analysis scan

- xray/commands/audit/scarunner.go
- xray/commands/audit/scarunner_test.go
-----
The issue was that we determined if the scan should be recursive based on a wrong variable.
condition was (len on string):
```
len(currentWorkingDir) > 0
```
and fixed to the correct one (len on param list):
```
len(params.workingDirs) == 0
```
> Fix - scan SCA recursive only when workingDirs not provided

- buildscripts/download-jars.sh
-----
Download gradle-dep-tree.jar and maven-dep-tree.jar to `xray/commands/audit/sca/java/resources/` instead of just `xray/commands/audit/sca/java/`. Right now, this problem doesn't seem to have an impact as the jars under `xray/commands/audit/sca/java/resources/` look accurate.
> download-jars.sh downloads to the wrong path

- artifactory/commands/transferfiles/state/statemanager.go
-----
There's an issue that needs fixing: 
**Steps to reproduce**
Execute `jf rt transfer-files` twice. The second run will show incorrect progress in Phase 3.
**The root cause**
Phase 3 doesn't retain information, yet it fetches the count of transferred files from the prior run.
> Transfer - Phase 3 progress wrongly adds transferred files

- artifactory/commands/transferfiles/fileserror.go
- artifactory/commands/transferfiles/state/runstatus.go
- artifactory/commands/transferfiles/state/statemanager.go
- artifactory/commands/transferfiles/state/statemanager_test.go
- artifactory/commands/transferfiles/state/utils.go
- artifactory/commands/transferfiles/status.go
- artifactory/commands/transferfiles/transfer.go
-----
Concurrent updates to state variables in certain scenarios can lead to inaccuracies, causing unexpected behaviors. An instance highlighting this concern involves a "negative" value within the "Delayed files" category:
The objective of this pull request is to improve accuracy by adjusting these values using the native `atomic` package.
> Transfer - Make high frequency changes atomic

- artifactory/commands/transferfiles/transfer.go
- artifactory/utils/weblogin.go
- utils/coreutils/profiler.go
- utils/coreutils/profiler_test.go
-----
Example output:
```
2023/12/14 18:12:57 [Info] ========== Running 'Full Transfer Phase' for repo 'docker-local-big2'... ==========
2023/12/14 18:13:17 [Info] Starting thread dumping...
2023/12/14 18:13:20 [Info] ========== Thread dump #0 ==========
goroutine profile: total 60
16 @ 0x103c7ce 0x104c2e5 0x191013d 0x106cce1
8 @ 0x103c7ce 0x1069e25 0x1954ede 0x1941790 0x16de2a2 0x106cce1
ransferfiles/utils.go:238
ransferfiles/utils.go:412
4 @ 0x103c7ce 0x100952d 0x1009132 0x12f9eb9 0x12fabbc 0x12f951f 0x106cce1
4 @ 0x103c7ce 0x1035bf7 0x1066e25 0x10d8587 0x10d987a 0x10d9868 0x12045a5 0x1210ce5 0x125ebbb 0x10fbf38 0x125ed9e 0x125c370 0x12605b1 0x12605b2 0x1260639 0x12652cb 0x1263133 0x12fa14d 0x12fa14e 0x106cce1
...
```
> Transfer - Generate a thread dump before a graceful stop

- artifactory/commands/transferfiles/manager.go
- artifactory/commands/transferfiles/manager_test.go
- go.mod
- go.sum
-----
Depends on https://github.com/jfrog/gofrog/pull/42.
Tests: https://github.com/jfrog/jfrog-cli/pull/2384.
At times, the chunk uploader might have no upload tasks, resulting in setting the finish notification before all file uploads are completed. This could cause the runProducerConsumers to exit prematurely without finishing the uploading jobs.
When tasks are present in the queue without a polling task manager, it may lead to an increase in curProcessedUploadChunks without a corresponding decrease. This situation can escalate, especially when there are enough future upload tasks, potentially causing a deadlock by increasing curProcessedUploadChunks to the maximum number of allowed worker threads.
To resolve this, we reset the finish notification to ensure no remaining upload tasks …
> Transfer - The runProducerConsumers method might terminate prematurely

- artifactory/commands/transferfiles/localgeneratedfilter.go
- artifactory/commands/transferfiles/localgeneratedfilter_test.go
-----
Certain files, locally generated in Artifactory, shouldn't be transferred.
The `.jfrog` directory, unintentionally included in Docker repository transfers, is triggering errors documented in a CSV file:
```csv
docker-local,.jfrog,,0,false,0,false,FAIL,404,,2023-12-21T16:31:01Z
```
The central cause of the transfer issues stemmed from an incorrect path specification within the locally generated API call. The path `./.jfrog` was inadvertently used, whereas the accurate path should have been solely `.jfrog`. This discrepancy led to the errors encountered.
> Transfer - Attempt to transfer ".jfrog" directory in Docker repositories

- xray/commands/audit/sca/common_test.go
- xray/commands/audit/sca/java/deptreemanager.go
-----
This PR fixes the bug of memory & time explosion while constructing Gradle/ Maven dependencies tree in big projects
A limitation to the number of impact paths per dependency was set to 10 (per project's module)
> Fix memory & time explosion during dependency tree construction for java based projects

- xray/commands/audit/audit.go
- xray/commands/audit/auditparams.go
- xray/commands/audit/scarunner.go
- xray/commands/audit/scarunner_test.go
-----
This PR improves the detection of whether or not to apply a recursive scan
> Improve recursive scan detection

- utils/java/mvn.go
> Optimization to clearMavenDepTreeRun call

- common/project/projectconfig.go
-----
When refactoring the code to another location `GetRepoConfigByPrefix` was changed and did not join the errors by mistake.
https://github.com/jfrog/jfrog-cli-core/commit/8e451d1cd6d5a7703f4851f1b840ab386ab97106#diff-374058d0b4f3d0f1fc734af2925a8e92e53a4f18e4372f5f7b34cf3864f5c6fcL129
return the join for the errors.
> Join error on GetRepoConfigByPrefix

- go.mod
- go.sum
- lifecycle/common.go
- lifecycle/createcommon.go
- lifecycle/createfrombuilds.go
- lifecycle/createfrombundles.go
- lifecycle/promote.go
-----
Depends on https://github.com/jfrog/jfrog-client-go/pull/893
Breaking changes:
- Changed signature of creation and promotion commands.
- Removed the `overwrite_existing_artifacts` promotion option that has been decommissioned as of 7.75.0 (both from UI and API).
Improvement:
- Support for include/exclude repositories in release bundle promotion.
> Artifactory Release Lifecycle Management - Modify release bundle promotion properties

- tests/testdata/maven-example-with-many-types/pom.xml
- utils/java/deptreemanager.go
- utils/java/gradle.go
- utils/java/mvn.go
- utils/java/mvn_test.go
- utils/xray/xrayutils.go
> Maven support for curation audit cmd.

- plugins/common/config.go
-----
Resolve https://github.com/jfrog/jfrog-cli/issues/2424
The build name and build-number arguments can be supplied via environment variables. `buildConfiguration.GetBuildName()` and `buildConfiguration.GetBuildNumber()` are handling these cases.
Hence, it also makes sense not to include any arguments in this command.
> Fix panic in build-scan without arguments

- utils/java/mvn.go
- utils/java/mvn_test.go
> Curation - Recognize 403 or 500 errors from the tree builder

- utils/python/utils.go
-----
the test `TestAddRepoToPyprojectFile` was failing due error to resolve dependencies.
the problem is that the test should not have tried to run poetry update command as it attempts to resolve dependencies from a non-existing artifactory repo.
Fix:
Split functionality of `addRepoToPyprojectFile` and `poetry update` to a different function
> Fix poetry failing test

- artifactory/commands/npm/publish.go
- artifactory/commands/npm/publish_test.go
-----
When reading for an already packed npm package, there was a missing file path that wasn't set because of the changes to handle workspaces.
This PR should fix it by setting the file path.
> Fix npm publish with provided tarball

- artifactory/utils/npm/pack.go
- tests/testdata/npm-workspaces/package.json
-----
modified the `getPackageFileNameFromOutput` function to extract .tgz files from the output, which as we saw, can be different when pre pack scripts exists or any other parameters which can effect the output of the npm pack command
> Fix npm pack command with prePack script

- artifactory/utils/weblogin.go
- common/commands/config.go
- general/login/login.go
-----
Revise the web login commands errors (`jf login` & `jf c add` with Web Login) to advise executing `jf c add` if the Artifactory version is below 7.64.0.
> Update web login prompts

- artifactory/commands/golang/go.go
- artifactory/commands/golang/gopublish.go
- artifactory/commands/npm/npmcommand.go
- artifactory/commands/npm/publish.go
- artifactory/commands/python/poetry.go
- artifactory/commands/python/python.go
- common/build/buildutils.go
- common/build/buildutils_test.go
-----
Revert the commit that was introduced via #1201, because it breaks the default module name for a few package managers.
> Revert commit "Fix root module name handling in build info collection"

- plugins/components/commandcomp.go
- plugins/components/conversionlayer.go
- plugins/components/conversionlayer_test.go
-----
For embedded plugins, when using its `context` flags where reported as set when they are not.
Fixing: `(c *Context) IsFlagSet(flagName string) bool`
> embedded plugin context - don't set flags if not exists

- artifactory/commands/buildinfo/publish.go
- artifactory/commands/commandssummaries/buildinfosummary.go
- artifactory/commands/commandssummaries/buildinfosummary_test.go
- artifactory/commands/commandssummaries/testdata/modules.md
- artifactory/commands/commandssummaries/uploadsummary.go
- artifactory/commands/commandssummaries/utils.go
- artifactory/commands/commandssummaries/utils_test.go
- artifactory/commands/generic/upload.go
-----
Improvements:
1. We clear filter on links to make sure the artifact is not masked and will be shown.
2. Remove the projectKey query param to avoid conflict with repositories that are not part of the project.
> Improve artifacts links in command summaries

- artifactory/commands/commandssummaries/buildinfosummary.go
- artifactory/commands/commandssummaries/buildinfosummary_test.go
> Skip modules without artifacts in command summary

- artifactory/commands/mvn/mvn.go
> Mvn - avoid parsing build info when it has not been collected

- artifactory/commands/commandssummaries/buildinfosummary.go
- artifactory/commands/commandssummaries/buildinfosummary_test.go
- artifactory/commands/commandssummaries/testdata/multiarch-image1.md
- artifactory/commands/commandssummaries/utils.go
- artifactory/utils/container/buildinfo.go
-----
- Ignore Docker attestation modules in the summary.
- Add a link to the Docker package in Artifactory in the multi-arch collapsible view.
<pre><details><summary>linux/amd64/multiarch-image:1 <a href=https://myplatform.com/ui/packages/docker:%2F%2Flinux/amd64/multiarch-image/sha256__aee9d258e62f0666e3286acca21be37d2e39f69f8dde74454b9f3cd8ef437e4e>(View 🐸)</a></summary>
📦 docker-local
└── 📁 multiarch-image
└── 📁 sha256:552ccb2628970ef526f13151a0269258589fc8b5701519a9c255c4dd224b9a21
└── <a href=https://myplatform.com/ui/repos/tree/General/docker-local/multiarch-image/sha256:552ccb2628970ef526f13151a0269258589fc8b5701519a9c255c4dd224b9a21/sha256__aee9d258e62f0666e3286acca21be37d2e39f69f8dde74454b9f3cd8ef437e4e?clearFilter=true …
> Job Summary - Handle Docker Multi-Module Sections Separately

- utils/coreutils/coreconsts.go
Rename the JFROG_CLI_TRANSITIVE_DOWNLOAD_EXPERIMENTAL environment variable to JFROG_CLI_TRANSITIVE_DOWNLOAD, while still supporting the old name.
> Rename the JFROG_CLI_TRANSITIVE_DOWNLOAD_EXPERIMENTAL environment variable

- artifactory/commands/transferfiles/transfer_test.go
- go.mod
- go.sum
-----
This PR updates the JFrog CLI Code to use the latest development branch.
Prior to this pull request (PR), the JFrog CLI client was generating `/api/repositories?type=federated&packageType=`. We can see that the packageType is empty. The new code inside JFrog client Go generates it better like this: `/API/repositories?type=federated`. 
Following tests were modified as the URI for query parameters was changed and resulted in more accurate results
>  Update go.mod and go.sum with latest version of jfrog-client-go

- artifactory/utils/commandsummary/buildinfosummary.go
- artifactory/utils/commandsummary/buildinfosummary_test.go
- artifactory/utils/commandsummary/markdownConfig.go
- artifactory/utils/testdata/command_summaries/basic/generic-module.md
- artifactory/utils/testdata/command_summaries/basic/maven-module.md
- artifactory/utils/testdata/command_summaries/basic/maven-nested-module.md
- artifactory/utils/testdata/command_summaries/extended/generic-module.md
- artifactory/utils/testdata/command_summaries/extended/maven-module.md
- artifactory/utils/testdata/command_summaries/extended/maven-nested-module.md
-----
This PR separates the logic for generating markdown related to modules.
The module display is now divided into two subsections:
Modules with scan results (currently, this applies only to Docker images).
Modules without scan results (e.g., an npm module that is packaged into a tar file and then deleted, which we currently cannot scan easily with a JF command).
Introduced refactoring to improve code maintainability for the future.
Made minor adjustments to titles and UI elements for a better user experience.
##
> Command Summary - Separate Module Table View from Artifacts Tree

- artifactory/commands/python/twine.go
- artifactory/utils/commandsummary/buildinfosummary.go
- common/commands/configfile.go
- go.mod
- go.sum
- utils/coreutils/cmdutils.go
-----
Depends on https://github.com/jfrog/build-info-go/pull/276
> Add twine support

- common/commands/config.go
- utils/ioutils/ioutils.go
-----
Following the API Key [deprecation process](https://jfrog.com/help/r/jfrog-platform-administration-documentation/jfrog-api-key-deprecation-process), this PR removes the API Key suggestion (wording only) from the config command.
API Key will still be support in the CLI if the JPD supports it (see the link above for more details).
> Remove API Key suggestion from config command

- artifactory/utils/commandsummary/buildinfosummary.go
- artifactory/utils/container/buildinfo.go
- artifactory/utils/container/image.go
- artifactory/utils/container/image_test.go
-----
Fix the missing org part on the docker build summary (view) link.
The current link points to `<ArtifactoryURL>/ui/packages/docker:%2F%2F<image-name>/sha256__AAA`
While it should point to `<ArtifactoryURL>/ui/packages/docker:%2F%2F<org-name>%2F<image-name>/sha256__AAA` when org name is part of the docker image name.
> Fix docker build summery broken link (missing org)

- go.mod
- go.sum
Fix a bug where after a file is downloaded from Artifactory, there's one temporary file that remains in the OS temp dir. This fix removes this temporary file.
Depends on https://github.com/jfrog/jfrog-client-go/pull/1036
> Remove remaining temp file after Artifactory download

- artifactory/utils/commandsummary/commandsummary.go
- artifactory/utils/commandsummary/markdownConfig.go
Make the `CheckExtendedSummaryEntitled` API public, so that it can be used by the `jfrog-cli-security` module.
> Make the CheckExtendedSummaryEntitled API public

- common/spec/specfiles.go
- common/spec/specfiles_test.go
-----
Adding a function to create a spec from provided parameters
> Create spec from variables

- plugins/components/commandcomp.go
- utils/coreutils/coreconsts.go
-----
Implemented functionality to add a flag to the context after its creation.
Introduced two constant variables.
> Internal - Added the ability to add flag to existing  context

- .github/workflows/test.yml
Install Mono on Ubuntu to run nuget.exe, due to this issue on Ubuntu 24 that hasn't been fixed yet - https://github.com/NuGet/setup-nuget/issues/168 : `nuget: 2: mono: not found error on nuget pack command in Ubuntu LTS 24.04.1`
> Fix NuGet related tests

- go.mod
- go.sum
- utils/usage/visibility_system_manager.go
- utils/usage/visibility_system_manager_test.go
Depends on https://github.com/jfrog/jfrog-client-go/pull/1061
Send the `PostMetric` API a struct, instead of a JSON,
> Internal API - Visibility System improvements

- go.mod
- go.sum
- utils/usage/visibility_system_manager.go
- utils/usage/visibility_system_manager_test.go
Depends on https://github.com/jfrog/jfrog-client-go/pull/1062
> Internal API - New `product_version` field added to the Visibility Metric

- artifactory/commands/npm/npmcommand.go
Reduced the minimum npm version for supporting scoped auth, from 9.3.1 to 9.2.0.
This resolves an issue, where when running `jf npm install` with npm 9.2.0, JFrog CLI doesn't authenticate with the JFrog Platform.
> Reduced the min npm version for supporting scoped auth

- utils/tests/test_cli.go
-----
Add option to run test CLI with command that return error as well
> Test Cli outputs of cmd with errors

- utils/coreutils/cmdutils.go
> Added support for printing red & green colored text

- go.mod
- go.sum
- utils/coreutils/utils.go
-----
Following https://github.com/jfrog/jfrog-cli/issues/2833
> Create temp dir if doesnt exist

- go.mod
- go.sum
- lifecycle/common.go
- lifecycle/common_test.go
- lifecycle/promote.go
-----
Adding a new flag for release bundle promote (RBP) command named 'operation'.
> Adding `--operation` flag for the release bundle promote command

- artifactory/utils/yarn/configget.go
- artifactory/utils/yarn/versionVerify.go
- artifactory/utils/yarn/versionVerify_test.go
> Verify supported `Yarn` version

- common/build/buildinfoproperties.go
- common/commands/configfile.go
- common/commands/flag_test.go
- common/project/projectconfig.go
- go.mod
- go.sum
-----
depends on :-
1. https://github.com/jfrog/jfrog-cli/pull/2883
2. https://github.com/jfrog/build-info/pull/818
> Extended support for snapshot policy for resolver in Maven Projects

- plugins/components/conversionlayer.go
-----
This PR updates the handling of boolean flags (`BoolFlag`) in the `fillFlagMaps` function.
Previously, `BoolFlag`s were only added to the internal context (`c.boolFlags`) if they were explicitly set by the user:
```go
if boolFlag, ok := flag.(BoolFlag); ok && baseContext.IsSet(boolFlag.Name) {
```
This caused flags with a default value of `true` to be skipped unless manually provided.
The updated logic:
```go
if boolFlag, ok := flag.(BoolFlag); ok {
val := getValueForBoolFlag(boolFlag, baseContext)
if baseContext.IsSet(boolFlag.Name) || val {
c.boolFlags[boolFlag.Name] = val
}
}
```
Now, a boolean flag is included if:
- It was explicitly set by the user (`baseContext.IsSet(...)`)
- **OR** its resolved value is `true` (e.g., default `true`)
This ensures all effective boolean flags …
> Include default true bool flags in CLI flag mapping

- common/project/projectconfig.go
-----
Add twine as project type (package manager) to support `jf setup twine` command
> Add twine package manager type

- common/commands/configfile.go
- common/commands/configfile_test.go
- common/project/projectconfig.go
- common/project/projectconfig_test.go
Added Ruby in order to use ruby-config
> added-ruby-to-projects

- common/spec/specfiles.go
- common/spec/specfiles_test.go
-----
Issue: The CLI failed to handle build numbers containing forward slashes (e.g., 1-slash/slash) when creating a Release Bundle using jf rbc. This resulted in a 404 Not Found error because the slash in the build number was incorrectly parsed, splitting it into separate segments.
Solution: The issue was fixed by escaping forward slashes in both buildName and buildNumber, This ensures that the build string is correctly parsed as a single entity.
> fix slash issue in build name, number in rbc

- common/commands/config.go
- general/token/oidctokenexchange.go
- go.mod
- go.sum
- utils/coreutils/coreconsts.go
> Add OIDC context struct

- artifactory/commands/utils/templateutils.go
- go.mod
- go.sum
-----
Added a `ConvertTemplateToMaps` method to parse the template JSON file containing repository configuration details.
> Method-to-read-repo-template-configs

- artifactory/utils/utils.go
-----
This PR introduces a new utility function, `ValidateRepoType`, to the Artifactory utils package. This function allows consumers to validate that a given repository exists and is of the expected `packageType` (e.g., `vscode`, `jetbrains`).
- **New Function:**
- `ValidateRepoType(repoKey, serviceDetails, expectedType string) error`
- Fetches repository details and checks that the `packageType` matches the expected value.
- Returns a clear error if the type does not match.
- **Intended Usage:**
- Designed for use in CLI commands and integrations that require strict repository type validation (e.g., IDE integrations in `jfrog-cli-artifactory`).
- Consumed by `jfrog-cli-artifactory` for VSCode and JetBrains IDE integrations.
https://github.com/jfrog/jfrog-cli-artifactory/pull/111
> Added ValidateRepoType method in utils.

- common/commands/command.go
- common/commands/metrics_collector.go
- common/commands/metrics_collector_test.go
- plugins/components/commandcomp.go
- plugins/components/conversionlayer.go
- utils/metrics/metrics.go
- utils/usage/visibility/commands_count_metric.go
- utils/usage/visibility/commands_count_metric_test.go
-----
The existing usage metrics collects only the command name. This PR adds more details into usage metrics to understand jfrog cli command usage
> Improve Usage metrics collection on jfrog-cli

- utils/image/base64converter.go
- utils/image/base64converter_test.go
- utils/markdown/imagereplacer.go
- utils/markdown/imagereplacer_test.go
-----
Converting local images and refs to base64 for markdown files
> Add image embedding functionality for Markdown with base64 conversion
