- artifactory/commands/generic/props.go
- artifactory/commands/golang/go.go
- artifactory/commands/npm/installorci.go
- artifactory/commands/repository/repository.go
- artifactory/utils/delete.go
- artifactory/utils/docker/buildinfo.go
- artifactory/utils/docker/docker.go
- artifactory/utils/download.go
- artifactory/utils/golang/project/project.go
- artifactory/utils/pip/dependencies/dependencies.go
- artifactory/utils/repositoryutils.go
- artifactory/utils/upload.go
- artifactory/utils/utils.go
- go.mod
- utils/config/tokenrefresh.go
Duplicate of :https://github.com/jfrog/jfrog-cli/pull/818
> Artifactory services manager interface

- artifactory/commands/generic/download.go
Fixes https://github.com/jfrog/jfrog-cli/issues/824
> Bugfix - Download & Sync command fails in Windows environment

- artifactory/commands/mvn/mvn.go
- artifactory/utils/buildinfoproperties.go
Resolves https://github.com/jfrog/jfrog-cli/issues/790
> Allow disabling maven artifacts deployment

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/test.yml
- README.md
* Add tests on GitHub actions
* Add PR and issues templates
* Fix tests instructions in README
> Add automation

- README.md
- tests/jfrogclicore_test.go
- utils/tests/utils.go
> Create tests package, run unit-tests with temporary JFROG_CLI_HOME_DIR

- artifactory/utils/docker/buildinfo.go
- artifactory/utils/docker/docker.go
> Bugfix - docker pull fails to collect buildinfo from remote repo

- artifactory/utils/docker/buildinfo.go
> Bugfix - Docker push fails to update layers properties

- artifactory/commands/repository/delete.go
-----
Depends on https://github.com/jfrog/jfrog-client-go/pull/209
Precondition for https://github.com/jfrog/jfrog-cli/pull/847
> Allow deleting repo by pattern

- .github/workflows/test.yml
- go.mod
> Run tests on pull requests

- artifactory/commands/golang/go.go
- artifactory/commands/golang/go_test.go
- artifactory/commands/golang/gopublish.go
- artifactory/utils/golang/project/archive.go
- artifactory/utils/golang/project/project.go
- go.mod
-----
Fixes https://github.com/jfrog/jfrog-cli/issues/763
> Support Go get command

- artifactory/commands/dotnet/dotnetcommand.go
- artifactory/commands/dotnet/dotnetcommand_test.go
- artifactory/commands/dotnet/testdata/slnDir/projTwo.vbproj
- artifactory/utils/dotnet/solution/project/project.go
- artifactory/utils/dotnet/solution/solution.go
- artifactory/utils/dotnet/solution/solution_test.go
Depends on [client#218](https://github.com/jfrog/jfrog-client-go/pull/218)
> Nuget support .*proj files

- artifactory/commands/generic/download.go
- artifactory/commands/generic/generic.go
- artifactory/commands/generic/upload.go
- artifactory/commands/npm/publish.go
- artifactory/utils/buildutils.go
>   Added detailed summary support for upload command

- utils/config/config_test.go
> Fix config test linter error

- artifactory/commands/gradle/gradle.go
- artifactory/commands/mvn/mvn.go
-----
Update Gradle extractor to 4.18.0
Update Maven extractor to 2.20.0
> Update Maven and Gradle extractors

- artifactory/commands/repository/template.go
> adding xrayIndex JSON key for remote repos

- plugins/components/conversionlayer.go
- plugins/components/structure.go
> Add "SkipFlagParsing" option for plugins

- artifactory/commands/buildinfo/addgit.go
- go.mod
Depends on [jfrog-client-go#225](https://github.com/jfrog/jfrog-client-go/pull/225)
> Support GetBuildInfo change

- artifactory/commands/buildinfo/addgit.go
- go.mod
Depends on [jfrog-client-go/pull/227](https://github.com/jfrog/jfrog-client-go/pull/227)
> Support GetBuildInfo api change

- artifactory/commands/generic/download.go
- artifactory/commands/generic/upload.go
> Bugfixed - progress bar got stuck when combined with --sync-delete

- artifactory/commands/generic/download.go
- artifactory/commands/generic/upload.go
- artifactory/utils/download.go
- artifactory/utils/upload.go
- artifactory/utils/utils.go
> Rename Progress to ProgressMgr 

- artifactory/commands/mvn/mvn.go
> Bugfix - Maven args with spaces

- artifactory/commands/pip/install.go
- artifactory/utils/pip/dependencies/dependencies.go
- artifactory/utils/pip/dependencies/dependencies_test.go
> Improve pip-install dependencies checksum collection

- artifactory/commands/npm/installorci.go
- artifactory/commands/npm/installorci_test.go
> Improve npm dependencies checksum collection

- artifactory/commands/buildinfo/addgit.go
- artifactory/commands/buildinfo/addgit_test.go
- artifactory/commands/buildinfo/publish.go
> Buildinfo: Support list of Vcs

- artifactory/commands/generic/copy.go
- artifactory/commands/generic/delete.go
- artifactory/commands/generic/move.go
- artifactory/commands/generic/props.go
- artifactory/commands/generic/search.go
> Parallel move and copy commands

- artifactory/commands/generic/copy.go
- artifactory/commands/generic/delete.go
- artifactory/commands/generic/download.go
- artifactory/commands/generic/move.go
- artifactory/commands/generic/props.go
- artifactory/spec/builder.go
- artifactory/spec/specfiles.go
- artifactory/utils/search.go
> Support 'include-deps' and 'exclude-artifacts' flags for search-based commands

- artifactory/commands/config.go
- artifactory/commands/config_test.go
> Fix importing config with refreshable token

- artifactory/commands/generic/upload.go
- artifactory/spec/builder.go
- artifactory/spec/specfiles.go
-----
Depends on: https://github.com/jfrog/jfrog-client-go/pull/272
Precondition for: https://github.com/jfrog/jfrog-cli/pull/959
Add the 'AddedProps' field to the file spec to support it in upload and release bundle commands.
> Add 'AddedProps' field to file spec

- artifactory/utils/repositoryutils.go
> Add error handling for non-existent repositories

- artifactory/commands/generic/delete.go
> Remove redundant "quiet" field from DeleteCommand

- artifactory/commands/usersmanagement/groupcreate.go
- artifactory/commands/usersmanagement/groupdelete.go
- artifactory/commands/usersmanagement/groupupdate.go
- artifactory/commands/usersmanagement/userscreate.go
- artifactory/commands/usersmanagement/usersdelete.go
> New Users management commands

- artifactory/commands/buildinfo/adddependencies.go
- artifactory/commands/generic/upload.go
- artifactory/spec/builder.go
- artifactory/spec/specfiles.go
- go.sum
> ant pattern

- artifactory/commands/buildinfo/adddependencies.go
- artifactory/commands/generic/props.go
- artifactory/commands/generic/search.go
- go.mod
- go.sum
-----
Related PR: 
* https://github.com/jfrog/jfrog-cli/pull/989
> Add 'from-rt' flag to 'bad' command

- artifactory/utils/dependenciesutils.go
> Download JARs - improve logs

- artifactory/commands/permissiontarget/permissiontarget.go
-----
Depends on [jfrog/jfrog-client-go#292](https://github.com/jfrog/jfrog-client-go/pull/292)
> Support permission target structure change

- artifactory/utils/container/buildinfo.go
- artifactory/utils/container/image.go
- artifactory/utils/container/image_test.go
> Container - Validate docker domain

- artifactory/commands/npm/installorci.go
- artifactory/commands/npm/installorci_test.go
> Add hierarchical dependencies for npm

- artifactory/commands/utils/configfile.go
> Update NuGet errror when no servers configured

- .github/workflows/test.yml
> Add GOPROXY: direct

- artifactory/commands/buildinfo/addgit.go
- artifactory/utils/repositoryutils.go
- common/commands/config.go
- general/cisetup/cisetup.go
- general/cisetup/pipelinesconfig.go
- general/cisetup/pipelinesyaml.go
- general/cisetup/pipelinesyaml_test.go
- general/cisetup/techindicators.go
- general/cisetup/techindicators_test.go
- go.mod
- go.sum
- utils/config/config.go
- utils/ioutils/ioutils.go
- utils/ioutils/promptstrings.go
> New Ci-setup command 

- plugins/signature.go
> Fix plugin description

- artifactory/utils/utils.go
- go.mod
- go.sum
> Remove duplicate argument in ServicesManagers

- plugins/pluginmain.go
> Fix plugins help description

- general/cisetup/pipelinesyaml.go
> Change JFROG_BUILD_RESULTS to JFROG_BUILD_STATUS

- artifactory/commands/gradle/gradle.go
- artifactory/commands/mvn/mvn.go
> Upgrade the maven and gradle extractors

- artifactory/commands/buildinfo/publish.go
- artifactory/commands/distribution/createbundle.go
- artifactory/commands/distribution/signBundle.go
- artifactory/commands/distribution/updatebundle.go
- go.mod
- go.sum
> Add sha256 detailed-summary to release bundle

- general/cisetup/githubactionsfilegenerator.go
- general/cisetup/jenkinsfilegenerator.go
> ci-setup command - phrasing changes

- artifactory/commands/npm/installorci.go
> Changing the npmrc permissions

- general/cisetup/techindicators_test.go
> Fix TestTechIndicator tests

- artifactory/commands/yarn/yarn_test.go
> Tests for Yarn

- artifactory/commands/buildinfo/addgit_test.go
- utils/config/config_test.go
- utils/coreutils/coreconsts.go
- utils/coreutils/utils.go
> Remove JFROG_CLI_HOME and JFROG_CLI_OFFER_CONFIG env var

- artifactory/commands/buildinfo/adddependencies.go
- go.mod
- go.sum
> Upload symlinks with their names

- artifactory/commands/dotnet/dotnetcommand.go
- xray/utils/resultstable.go
> Add direct component to Xray scan results table

- artifactory/commands/golang/go.go
- artifactory/commands/golang/go_test.go
- artifactory/utils/golang/project/project.go
> Adapt to API changes in gocmd

- xray/utils/resultstable.go
> Temporarily removed ignore rule URL table

- artifactory/commands/gradle/gradle.go
- artifactory/commands/mvn/mvn.go
> Update extractors versions

- utils/config/config_test.go
> Fix TestConfigEncryption

- xray/commands/audit/gradle.go
- xray/commands/audit/javautils.go
- xray/commands/audit/mvn.go
> Maven and Gradle audit show no violations

- artifactory/commands/npm/publish.go
> Fix npm publish with build info

- artifactory/commands/npm/installorci.go
- artifactory/utils/npm/config-get.go
- artifactory/utils/npm/config-list.go
- artifactory/utils/npm/pack.go
- artifactory/utils/npm/version.go
- utils/npm/cmd.go
- utils/npm/list.go
- utils/npm/utils.go
- xray/commands/audit/scan.go
-----
Add support for recursive flag.
Change Indexing log message to include full file path.
> Xray-scan minor changes

- go.mod
- go.sum
- xray/utils/resultstable.go
- xray/utils/resultstable_test.go
> Omit duplicate components in Xray results tables

- README.md
> Add tests badges to README

- go.mod
- go.sum
- xray/commands/audit/gradle.go
- xray/commands/audit/javautils.go
- xray/commands/audit/mvn.go
- xray/commands/audit/npm.go
- xray/commands/audit/scan.go
- xray/utils/downloadindexer.go
- xray/utils/resultstable.go
> Add support for json output for the Xray's scan commands

- xray/commands/audit/mvn.go
- xray/commands/audit/mvn_test.go
> Remove --exclude-test-deps flag from mvn-audit

- utils/coreutils/utils.go
- utils/gradle/utils.go
- utils/mvn/utils.go
> Convert ExitCode Error

- utils/coreutils/coreconsts.go
- utils/coreutils/tableutils.go
- utils/coreutils/utils.go
- xray/utils/resultstable.go
> Xray tables support in non-terminal env

- utils/coreutils/coreconsts.go
- utils/coreutils/utils.go
- xray/commands/audit/javautils.go
- xray/commands/audit/npm.go
- xray/commands/audit/scan.go
- xray/utils/resultstable.go
- xray/utils/resultwriter.go
> Xray scan small fixes

- xray/utils/downloadindexer.go
> Use GraphScanMinVersion in CLI integration tests

- common/commands/config.go
- utils/config/config.go
- utils/config/tokenrefresh.go
- utils/coreutils/coreconsts.go
- utils/coreutils/utils.go
- utils/lock/lock.go
- utils/lock/lock_test.go
- xray/utils/downloadindexer.go
- xray/utils/downloadindexer_test.go
> Get Xray Indexer version from the Indexer itself

- artifactory/spec/specfiles.go
-----
PR fix : https://github.com/jfrog/jfrog-cli-core/pull/199
> Fix: Error description for symlinks archiving

- xray/commands/audit/mvn.go
> Remove unused code from Maven audit

- xray/utils/downloadindexer.go
> Fix Indexer move dir

- xray/utils/downloadindexer.go
- xray/utils/downloadindexer_test.go
> Fix Xray scan on Windows os

- utils/config/configtoken_test.go
> Remove unnecessary assert for access url

- artifactory/commands/npm/publish.go
-----
Fixes jfrog/jfrog-cli#1198
> v1: npm publish reads wrong package.json file

- artifactory/commands/npm/publish.go
-----
Fixes https://github.com/jfrog/jfrog-cli/issues/1198
> npm publish reads wrong package.json file

- .github/workflows/test.yml
> Remove M2_HOME from GitHub actions tests

- xray/utils/resultstable.go
- xray/utils/resultstable_test.go
-----
In case a violation/vulnerability/license doesn't contain any component - an error will be thrown
> Validate num of components in violations

- xray/utils/resultstable.go
-----
Fixes https://github.com/jfrog/jfrog-cli/issues/1225
> Fix Xray's scan "no context" message

- utils/mvn/utils.go
> Bugfix - 'getMavenHome' fails on windows OS

- artifactory/commands/mvn/mvn.go
-----
Related v2: https://github.com/jfrog/jfrog-cli-core/commit/06ec38ae32147fb11212bb58dd1da08c887332da
> Make "M2_HOME" env variable optional (v1)

- artifactory/commands/golang/publish.go
- artifactory/commands/oc/startbuild.go
- utils/coreutils/tableutils.go
-----
Small fixes:
* Avoid closing the zip temp file twice in go-publish.
* Check if running in terminal also when printing a message in a frame.
> Small fixes

- xray/commands/audit/gradle_test.go
- xray/commands/audit/javautils.go
-----
Fix missing java (Maven/Gradle) audit transitive dependencies
following [#1303 issue](https://github.com/jfrog/jfrog-cli/issues/1303)
> Fix java audit transitive dependencies

- artifactory/utils/npm/pack.go
-----
Enforce running `npm pack` without json output so our file name extraction will not fail.
> Run npm pack with json=false

- artifactory/utils/container/image.go
> Fix incorrect log message

- utils/mvn/utils.go
-----
Fix maven version validation parsing issue.
Following #264 issue
>   Fix maven version validation parsing

- artifactory/commands/buildinfo/adddependencies.go
- artifactory/commands/buildinfo/addgit.go
- artifactory/commands/buildinfo/buildappend.go
- artifactory/commands/buildinfo/clean.go
- artifactory/commands/buildinfo/collectenv.go
- artifactory/commands/buildinfo/promote.go
- artifactory/commands/buildinfo/publish.go
- artifactory/commands/buildinfo/xrayscan.go
- artifactory/commands/container/buildcreate.go
- artifactory/commands/container/pull.go
- artifactory/commands/container/push.go
- artifactory/commands/dotnet/dotnetcommand.go
- artifactory/commands/generic/download.go
- artifactory/commands/generic/upload.go
- artifactory/commands/golang/go.go
- artifactory/commands/golang/gopublish.go
- artifactory/commands/npm/publish.go
- artifactory/commands/oc/startbuild.go
- artifactory/commands/pip/install.go
- artifactory/commands/utils/npmcmdutils.go
- artifactory/utils/buildutils.go
- artifactory/utils/buildutils_test.go
- utils/gradle/utils.go
- utils/mvn/utils.go
- xray/commands/audit/javautils.go
> Bugfix wrong indication to collect build info

- artifactory/commands/utils/configfile.go
- artifactory/commands/utils/configfile_test.go
- general/cisetup/cisetup.go
- general/cisetup/githubactionsfilegenerator.go
- general/cisetup/jenkinsfiledslgenerator.go
- general/cisetup/jenkinsfilegenerator.go
- general/cisetup/pipelinesyaml.go
- general/cisetup/utils.go
- general/cisetup/utils_test.go
- general/envsetup/envsetup.go
- general/project/projectinit.go
- general/project/repoutils.go
- utils/coreutils/techutils.go
- utils/coreutils/techutils_test.go
> Add New Project Init Command

- artifactory/utils/buildutils.go
- artifactory/utils/buildutils_test.go
> Bugfix - CLI ignores project env var

- general/envsetup/envsetup.go
- general/project/projectinit.go
> Small changes to the new setup and project init commands

- xray/commands/audit/commonutils.go
-----
Dependency for https://github.com/jfrog/jfrog-cli/pull/1333
> Bugfix - audit ignores JFROG_CLI_BUILD_PROJECT env

- artifactory/commands/buildinfo/promote.go
> Bugfix - bp ignores JFROG_CLI_BUILD_PROJECT env

- go.mod
- go.sum
- xray/commands/scan/buildscan.go
-----
Depends on [jfrog/jfrog-client-go#492](https://github.com/jfrog/jfrog-client-go/pull/492)
> Return xray data url from build scan

- xray/commands/scan/buildscan.go
> Fix buildscan fail build falg

- xray/commands/audit/commonutils.go
- xray/commands/scan/scan.go
-----
Dependency for https://github.com/jfrog/jfrog-cli/pull/1350
> Allow fail=false in audit and scan commands

- xray/commands/scan/buildscan.go
> Print build scan url without log

- .github/workflows/test.yml
> Upgrade Go in tests to 1.17

- artifactory/commands/buildinfo/adddependencies.go
- artifactory/commands/buildinfo/buildappend.go
- artifactory/commands/golang/publish.go
- artifactory/commands/npm/installorci.go
- artifactory/commands/python/dependencies/cache_test.go
- artifactory/commands/python/dependencies/dependencies.go
- artifactory/commands/utils/npmcmdutils.go
- artifactory/commands/yarn/yarn.go
- artifactory/commands/yarn/yarn_test.go
- artifactory/utils/container/buildinfo.go
- artifactory/utils/dotnet/dependencies/assetsjson.go
- artifactory/utils/dotnet/dependencies/packagesconfig.go
- go.mod
- go.sum
-----
Following jfrog/build-info-go#49 changes.
> Remove pointer from embedded checksum struct

- xray/commands/scan/dockerscan.go
> update DockerScanMinXrayVersion to 3.40.0

- artifactory/commands/npm/publish.go
- artifactory/commands/utils/npmcmdutils.go
- artifactory/utils/utils.go
- general/project/projectinit.go
- general/project/repoutils.go
- utils/coreutils/techutils.go
> Setup & init commands PR review fixes

- artifactory/commands/python/python.go
- go.mod
- go.sum
> Update go mod

- general/project/projectinit.go
- general/project/repoutils.go
- utils/coreutils/techutils.go
- utils/coreutils/techutils_test.go
> Add NuGet/Dotnet project init

- xray/commands/scan/dockerscan.go
- xray/commands/scan/scan.go
- xray/commands/utils.go
- xray/utils/downloadindexer.go
-----
1. Improve docker scan code and logs
2. Create a temp folder for the Xray indexer app to run at.
> improve docker scan command

- go.sum
- xray/commands/scan/dockerscan.go
- xray/commands/scan/scan.go
- xray/commands/utils.go
- xray/utils/downloadindexer.go
> Improve docker scan

- distribution/commands/createbundle.go
- distribution/commands/deletebundle.go
- distribution/commands/distributebundle.go
- distribution/commands/signBundle.go
- distribution/commands/updatebundle.go
> Move Distribution commands from Artifactory

- artifactory/commands/buildinfo/adddependencies.go
> Add module type to dependencies of build-add-deps command

- artifactory/commands/npm/publish.go
- artifactory/commands/utils/conditionaluploadutils.go
- xray/commands/scan/scan.go
-----
Also, restructure conditional upload to use a scan function from variable.
> Conditional upload to run with fail true

- artifactory/commands/npm/common.go
- artifactory/commands/npm/installorci_test.go
- artifactory/commands/npm/publish.go
- artifactory/commands/yarn/yarn.go
- go.mod
- go.sum
- xray/commands/audit/npm/npm.go
- xray/commands/audit/npm/npm_test.go
-----
Following other PR changes: https://github.com/jfrog/build-info-go/pull/46
> Move npm-utils to diff package

- artifactory/utils/dotnet/solution/solution.go
- go.mod
- go.sum
-----
The IsWindows() function is found in jfrog-client-go and in jfrog-cli-core, so it's preferred to use the one in jfrog-cli-core.
> Use coreutils

- artifactory/commands/python/dependencies/dependencies.go
- artifactory/utils/dotnet/solution/solution.go
- go.mod
- go.sum
> Limit the length of the RequestedBy buildinfo's field

- general/project/projectinit.go
- general/project/repoutils.go
- utils/coreutils/techutils.go
-----
Add docker to 'project init' output if 'docker' exists in PATH.
> Add docker to 'project init' output

- xray/utils/downloadindexer.go
-----
Following https://github.com/jfrog/jfrog-cli/issues/1453
> Improve indexer-app download log

- artifactory/commands/repository/repository.go
-----
following https://github.com/jfrog/jfrog-cli/issues/1464
> Improve error log for repo-create with invalid packageType/rclass

- .github/workflows/test.yml
-----
Add Go cache for Git action tests and remove unneccecary setup python action
> Add Go Cache for tests

- go.mod
- go.sum
- xray/commands/audit/npm/npm.go
-----
Depends on https://github.com/jfrog/build-info-go/pull/71
Fixes https://github.com/jfrog/jfrog-cli/issues/1475
> Bugfix - npm audit should not calculate checksums

- xray/audit/commonutils.go
- xray/audit/npm/npm_test.go
- xray/audit/nuget/nuget_test.go
> Fix audit tests

- utils/coreutils/tableutils.go
- xray/formats/conversion.go
- xray/formats/simplejsonapi.go
- xray/formats/table.go
- xray/utils/resultstable.go
- xray/utils/resultstable_test.go
- xray/utils/resultwriter.go
> Create an isolated API for the simple-json format

- xray/commands/scan/buildscan.go
-----
Following https://github.com/jfrog/jfrog-cli/issues/1512
> Fix invalid build-scan JSON output

- artifactory/commands/buildinfo/buildappend.go
- artifactory/commands/buildinfo/publish.go
> Bugfix - Encode build append args & build-info URL

- xray/commands/scan/scan.go
> Fix scan/docker-scan json output whit progress bar

- go.mod
- go.sum
-----
This pull request upgrade `golang.org/x/crypto` for the v1 branch, similarly to https://github.com/jfrog/jfrog-cli-core/pull/386 which did the same thing for the v2 branch.
> V1 - Upgrade jfrog-client-go & golang.org/x/crypto

- xray/commands/audit/generic/auditmanager.go
Signed-off-by: sverdlov93 <sverdlov93@gmail.com>
-----
Fix audit results overriding issue.
> Fix audit results overriding issue

- artifactory/commands/terraform/terraformpublish.go
-----
Change terraform layout in artifactory when uploading module
from : repoName/namespace/provider/moduleName/tag.zip
to: repoName/namespace/moduleName/provider/tag.zip
> Fix: Terraform module layout in Artifactory

- general/envsetup/envsetup.go
-----
1. Add verification to the user's password by using Artifactory's encryptedPassword API. 
2. Give the user a limited number of times to enter his password.
3. Change message for new/existing users.
> Improvement: setup command

- .github/workflows/frogbot-fix.yml
- .github/workflows/frogbot-scan-pr.yml
> Add Frogbot

- artifactory/utils/container/containermanager.go
> Add missing space to docker command log

- go.mod
- go.sum
> Remove repository name from artifacts' path field in the build-info JSON

- go.mod
- go.sum
- xray/commands/scan/buildscan.go
> Adding support for rescan flag on xr bs

- go.mod
- go.sum
- xray/commands/scan/buildscan.go
> Adding support for rescan flag on build-scan

- artifactory/commands/transfer/settings.go
- artifactory/utils/transfersettings.go
- utils/coreutils/coreconsts.go
- utils/coreutils/utils.go
- xray/utils/downloadindexer.go
-----
Added functions for saving and reading transfer settings. The settings are saved in the `.jfrog` directory.
> Change transfer threads number

- artifactory/commands/transferconfig/transferconfig.go
- artifactory/commands/transferconfig/transferconfig_test.go
-----
Related to https://github.com/jfrog/config-import/pull/3
> Use checkPermissions config-import API

- xray/commands/offlineupdate/offlineupdate.go
> offline db sync V3 handle error when downloading URLs

- artifactory/commands/transferfiles/delayedartifactshandler.go
> Transfer - fix delay writer initialization

- artifactory/commands/transferfiles/api.go
- artifactory/commands/transferfiles/utils.go
> Transfer - support skipped metadata file status

- artifactory/commands/transferfiles/delayedartifactshandler.go
- artifactory/commands/transferfiles/filesdiff.go
- artifactory/commands/transferfiles/fulltransfer.go
- artifactory/commands/transferfiles/manager.go
- artifactory/commands/transferfiles/utils.go
> Transfer - handle files of chunks failed to upload

- go.mod
- go.sum
> Failure to calculate final results summary during upload

- artifactory/commands/transferconfig/transferconfig.go
- artifactory/commands/transferconfig/transferconfig_test.go
- artifactory/commands/transferfiles/srcpluginservice.go
- artifactory/commands/transferfiles/transfer.go
- artifactory/commands/utils/transfer.go
> Transfer - verify the installation of the source Artifactory user plugin

- artifactory/commands/transferfiles/filesdiff.go
- artifactory/commands/transferfiles/fulltransfer.go
- artifactory/commands/transferfiles/state.go
- artifactory/commands/transferfiles/transfer.go
- artifactory/commands/transferfiles/utils.go
> Transfer - add pagination to full-transfer phase

- artifactory/commands/transferfiles/transfer.go
> Transfer files - reduce chunk size and threads

- artifactory/commands/transfer/settings.go
> Transfer - Increase threads limit to 256

- artifactory/commands/transfer/settings.go
- artifactory/commands/transferfiles/transfer.go
- artifactory/utils/transfersettings.go
-----
Show the current number of working threads on transfer-settings command.
> Show current transfer settings

- utils/coreutils/techutils.go
- xray/commands/audit/generic/auditmanager.go
- xray/utils/resultstable.go
> Add GetAllTechnologiesList function for audit commands

- artifactory/commands/transfer/settings.go
> Transfer - Increase threads limit to 1024

- artifactory/commands/transferfiles/fulltransfer.go
> Transfer - empty dirs should not have file names

- utils/coreutils/techutils.go
> Run only Pipenv Audit when both pipfile and setup.py exist

- artifactory/commands/transferfiles/filesdiff.go
- artifactory/commands/transferfiles/state.go
- artifactory/commands/transferfiles/state_test.go
- artifactory/commands/transferfiles/transfer_test.go
> Fix files diff handling range

- xray/commands/offlineupdate/offlineupdate.go
> Fix formatting of log message in Xray offline updates

- artifactory/commands/transferfiles/errorshandler.go
- artifactory/commands/transferfiles/errorshandler_test.go
- artifactory/commands/transferfiles/filesdiff.go
- artifactory/commands/transferfiles/summary.go
- artifactory/commands/transferfiles/summary_test.go
- artifactory/commands/transferfiles/transfer.go
- artifactory/commands/transferfiles/utils_test.go
- utils/log/log.go
> Fix: Transfer - Include only relevant errors files in summary

- artifactory/commands/transferconfig/transferconfig.go
- artifactory/commands/transferfiles/srcpluginservice.go
- artifactory/commands/utils/transfer.go
-----
Fix the following message:
`It looks like the config-import plugin is not installed on the source server.` -->
`It looks like the config-import plugin is not installed on the target server.`
> Transfer - fix plugin not installed message

- artifactory/commands/transfer/settings.go
- artifactory/commands/transferfiles/manager.go
- artifactory/commands/transferfiles/transfer.go
- artifactory/commands/transferfiles/utils.go
> Fix: Transfer - Stuck when reaching max tasks

- artifactory/commands/transferfiles/transfer.go
-----
Depends on https://github.com/jfrog/data-transfer/pull/26
> Update min data-transfer version to 1.3.1

- utils/coreutils/cmdutils.go
- utils/coreutils/tableutils.go
> Remove emoji from windows table empty message

- artifactory/commands/transferfiles/phase.go
- artifactory/commands/transferfiles/propertiesdiff.go
- artifactory/commands/transferfiles/transfer.go
- artifactory/commands/transferfiles/transfer_test.go
- artifactory/commands/transferfiles/transferfileprogress.go
- artifactory/commands/transferfiles/utils.go
- artifactory/utils/storageinfo.go
- artifactory/utils/storageinfo_test.go
- go.mod
- go.sum
-----
Depends on:
* https://github.com/jfrog/build-info-go/pull/93
* https://github.com/jfrog/jfrog-client-go/pull/633
Currently, we start storage info calculation right before the storage info retrieval. As a result, the storage info may not be updated, and may not contain new repositories.
* Create StorageInfoManager
* Refactor transfer
> Transfer - Missing repository in the repositories summary

- .github/workflows/test.yml
> Add data-race detector in tests

- utils/coreutils/coreconsts.go
> Add JFROG_CLI_FAIL_NO_OP environment variable

- artifactory/commands/transferfiles/transfer.go
- artifactory/commands/transferfiles/transfer_test.go
> Allow using snapshot data-transfer versions

- artifactory/commands/transferconfig/transferconfig.go
- artifactory/commands/transferconfig/utils.go
- go.mod
- go.sum
-----
Depends on https://github.com/jfrog/jfrog-client-go/pull/643
Fix the following issue in Artifactory 7:
```
409: Cannot decrypt without artifactory key file
```
> Transfer config - avoid encryption if not needed

- utils/mvn/utils.go
-----
should fix https://github.com/jfrog/jfrog-cli/issues/1683
> Support MAVEN_OPTS with multiple spaces between flags

- artifactory/commands/transferfiles/transfer.go
> Update min data-transfer version to 1.4.1

- artifactory/commands/gradle/gradle.go
- artifactory/commands/transferfiles/transfer.go
- artifactory/commands/transferfiles/transfer_test.go
-----
Fix the wrong number of repositories in the progress bar:
Instead of counting the number of repositories in the target server, count them in the source server.
> Transfer - fix number of reposiories in progress

- artifactory/commands/transferfiles/transfer.go
- artifactory/commands/transferfiles/transfer_test.go
-----
Include federated repositories in the list of repositories to transfer in the transfer-files commmand.
> Include federated repositories in files transfer

- artifactory/commands/transferfiles/manager.go
- artifactory/commands/transferfiles/state_test.go
- artifactory/commands/transferfiles/timeestimation.go
- artifactory/commands/transferfiles/timeestimation_test.go
- artifactory/commands/transferfiles/transfer.go
- artifactory/commands/transferfiles/transferfileprogress.go
- artifactory/utils/storageinfo_test.go
> Transfer - Add time estimation tests and temporary disable

- xray/audit/python/python.go
- xray/commands/audit/generic/auditmanager.go
> Take pip3 instead of pip on pip audit command

- artifactory/commands/transferfiles/timeestimation.go
- artifactory/commands/transferfiles/timeestimation_test.go
-----
Bug fix - panic could occur if average speeds is very low.
Improvement - Handle singular / plural and remove 0 remainders in the estimated remaining time string.
> Transfer - Estimated remaining time improvements

- artifactory/commands/python/python.go
-----
should fix missed error on https://github.com/jfrog/jfrog-cli/issues/1693
> Python - Return missed build info error

- artifactory/commands/python/python.go
> Fix Python command missing catch error

- artifactory/commands/utils/npmcmdutils.go
-----
should fix https://github.com/jfrog/jfrog-cli/issues/1579#issuecomment-1252751154
> Support Npm Auth with Identity/Reference Token

- artifactory/commands/transferfiles/utils.go
-----
This PR includes the implementation for a comment added for the code of https://github.com/jfrog/jfrog-cli-core/pull/564
> Transfer - Simplify handleFilesOfCompletedChunk

- artifactory/commands/python/python.go
- artifactory/commands/transferfiles/filesdiff.go
- artifactory/commands/transferfiles/fileserror.go
- artifactory/commands/transferfiles/fulltransfer.go
- artifactory/commands/transferfiles/manager.go
- artifactory/commands/transferfiles/transfer.go
- artifactory/commands/transferfiles/utils.go
- go.mod
- go.sum
> Transfer - Improve waiting time between phases

- artifactory/commands/transferfiles/utils.go
> Improve stopTransferInArtifactory context comment

- artifactory/commands/repository/repository.go
Signed-off-by: Michael Sverdlov <michaelsv@jfrog.com>
-----
should fix https://github.com/jfrog/jfrog-cli/issues/1708
> Fix repo create with contentSynchronisation issue

- artifactory/commands/transferfiles/delayedartifactshandler.go
> Builder can get stuck on delayed files upload

- artifactory/commands/transferfiles/phase_test.go
-----
TestStopGracefully fails in Windows - there may be still active threads.
https://github.com/jfrog/jfrog-cli-core/actions/runs/3174930156/jobs/5172340911#step:11:257
> Fix TestStopGracefully

- utils/coreutils/tableutils.go
-----
should fix https://github.com/jfrog/jfrog-cli/issues/1725 and https://github.com/jfrog/jfrog-cli/discussions/1713
> Fix Scan or Audit output results to file issue

- xray/audit/commonutils.go
- xray/audit/go/gloang_test.go
- xray/audit/go/golang.go
- xray/audit/java/gradle.go
- xray/audit/java/mvn.go
- xray/audit/npm/npm.go
- xray/audit/nuget/nuget.go
- xray/audit/python/python.go
- xray/audit/yarn/yarn.go
- xray/commands/audit/generic/auditmanager.go
Signed-off-by: Michael Sverdlov <michaelsv@jfrog.com>
-----
> Improve audit code

- xray/commands/audit/generic/auditmanager.go
- xray/commands/audit/generic/generic.go
> Add audit multiple directory support

- artifactory/commands/generic/gitlfsclean.go
-----
should fix https://github.com/jfrog/jfrog-cli-core/issues/587
> Fix wrong deleted files count on git-lfs command

- .github/workflows/frogbot-scan-and-fix.yml
- .github/workflows/frogbot-scan-pr.yml
-----
Update Frogbot to the most recent Go templates.
Should fix the following issue in scan-and-fix:
> Error: 5 [Error] upload code scanning failed with: POST https://api.github.com/repos/jfrog/jfrog-cli-core/code-scanning/sarifs: 403 Resource not accessible by integration []
Error: The process '/opt/hostedtoolcache/frogbot/[RELEASE]/x64/frogbot' failed with exit code 1
> Update Frogbot workflows

- artifactory/commands/transferfiles/status.go
> Transfer - fix "Transfer failures" status align

- artifactory/commands/transferfiles/status.go
- artifactory/commands/transferfiles/transferfileprogress.go
> Transfer - adding retry note to transfer failures status

- artifactory/commands/transferconfig/transferconfig_test.go
- artifactory/commands/transferfiles/transfer_test.go
- artifactory/utils/storageinfo.go
- common/tests/utils.go
- go.mod
- go.sum
-----
Depends on https://github.com/jfrog/jfrog-client-go/pull/671
> New distribution mock server

- artifactory/commands/transferfiles/status_test.go
> Fix transfer show status tests

- artifactory/commands/transferfiles/filesdiff.go
> Transfer - Shorten phase 2 docker AQL

- common/commands/config.go
- utils/ioutils/ioutils.go
-----
Add colors to the interactive questionnaire to highlight the field names:
> Improve interactive 'config add' UI

- artifactory/commands/transferfiles/transferfileprogress.go
- utils/progressbar/progressbarmng.go
> Fix go vet for progress bar

- artifactory/commands/transferfiles/status.go
- artifactory/commands/transferfiles/transferfileprogress.go
- artifactory/utils/storageinfo.go
- jfrog-cli-core/go.mod
> UI improvements for progress bar and status

- artifactory/utils/container/containermanager.go
-----
Disable the default 'docker scan' suggestion in native Docker commands.
> Disable default Docker scan suggestion

- jfrog-cli-core/go.mod
> Delete jfrog-cli-core dir

- artifactory/commands/buildinfo/adddependencies.go
- go.mod
- go.sum
- xray/commands/scan/scan.go
-----
Part of:
* https://github.com/jfrog/jfrog-client-go/pull/662
* https://github.com/jfrog/jfrog-cli/pull/1729
> Upload - Take into account the repository name with exclude pattern and include directory flags

- artifactory/commands/utils/dockercmdutils.go
- xray/commands/scan/dockerscan.go
> Fix docker scan by repo-path

- artifactory/commands/transferconfig/remoteurlchecker.go
- artifactory/commands/transferconfig/transferconfig.go
- artifactory/commands/transferconfig/transferconfig_test.go
- artifactory/commands/transferconfig/utils.go
- artifactory/commands/transferfiles/longpropertycheck.go
- artifactory/commands/utils/remoteurlchecker.go
- artifactory/commands/utils/transferconfigutils.go
- artifactory/commands/utils/transferconfigutils_test.go
-----
Depends on https://github.com/jfrog/config-import/pull/13
Check remote repositories using the `--prechecks` flag.
The CLI part PR is pending on https://github.com/jfrog/jfrog-cli/pull/1755
> Transfer config - Optionally check remote repositories URLs

- artifactory/commands/transferfiles/status_test.go
- utils/reposnapshot/node.go
- utils/reposnapshot/snapshotmanager.go
- utils/reposnapshot/snapshotmanager_test.go
> Transfer - fix possible race when finding directory node

- xray/audit/npm/npm.go
> Fix npm version log string

- artifactory/commands/transferfiles/status.go
- artifactory/commands/transferfiles/status_test.go
- utils/reposnapshot/snapshotmanager_test.go
> Fix transfer status tests

- artifactory/commands/container/containermanagerbase.go
- artifactory/commands/golang/gopublish.go
- artifactory/commands/transferconfig/transferconfig.go
- artifactory/commands/transferconfig/transferconfig_test.go
- artifactory/commands/transferfiles/transfer.go
- artifactory/commands/transferfiles/transfer_test.go
- artifactory/commands/utils/npmcmdutils.go
- artifactory/utils/container/containermanager.go
- utils/coreutils/utils.go
- xray/audit/commonutils.go
- xray/commands/scan/buildscan.go
- xray/commands/scan/dockerscan.go
- xray/commands/scan/scan.go
- xray/commands/utils.go
> Unite all minimum version validation functions

- artifactory/commands/generic/upload.go
- artifactory/commands/terraform/terraformpublish.go
- artifactory/commands/terraform/terraformpublish_test.go
- artifactory/utils/buildutils.go
- go.mod
- go.sum
-----
Depends on https://github.com/jfrog/build-info-go/pull/121
> Add build info collection support for Terraform

- xray/audit/commonutils.go
- xray/audit/python/python.go
- xray/audit/yarn/yarn.go
> Fail audit command for yarn v1

- xray/utils/resultwriter.go
- xray/utils/resultwriter_test.go
> Change convert scan to sarif headline

- artifactory/commands/terraform/terraformpublish.go
- artifactory/commands/terraform/terraformpublish_test.go
> Use server from Terraform project configuration

- artifactory/commands/transferinstall/datatransferinstall.go
- artifactory/commands/transferinstall/datatransferinstall_test.go
> Install Transfer Plugin - Support Artifactory product folder names with prefix/suffix

- artifactory/commands/transferfiles/manager.go
- artifactory/commands/transferfiles/phase.go
- artifactory/commands/transferfiles/status.go
- artifactory/commands/transferfiles/transfer.go
- artifactory/commands/transferfiles/transfer_test.go
- artifactory/commands/transferfiles/utils.go
- artifactory/commands/transferfiles/utils_test.go
> Transfer - Allow stopping from a different process

- artifactory/commands/transferfiles/manager.go
- artifactory/commands/transferfiles/state/state_test.go
- artifactory/commands/transferfiles/state/statemanager.go
- artifactory/commands/transferfiles/state/statemanager_test.go
- artifactory/commands/transferfiles/state/timeestimation_test.go
- artifactory/commands/transferfiles/status_test.go
- artifactory/commands/transferfiles/transferfileprogress.go
- artifactory/utils/transfersettings.go
- utils/progressbar/progressbarmng.go
-----
* Add skipped metadata files and files with long properties to the transferred files count
* Minor refactor
> Transfer - Count skipped files in the progress bar

- artifactory/commands/transferfiles/transfer.go
- utils/reposnapshot/snapshotmanager_test.go
> Transfer - Close the stop file after creation

- artifactory/commands/transferfiles/fulltransfer.go
- artifactory/commands/transferfiles/state/statemanager.go
- artifactory/commands/transferfiles/transfer.go
- artifactory/commands/transferfiles/transferfileprogress.go
> Transfer - reflect transferred units from snapshot in progress

- xray/utils/resultwriter.go
> Extract SplitScanResults

- artifactory/commands/golang/archive.go
- artifactory/commands/transferinstall/datatransferinstall_test.go
- artifactory/commands/utils/questionnaire.go
- distribution/commands/deletebundle.go
- utils/coreutils/tableutils.go
- utils/lock/lock_test.go
- xray/commands/audit/generic/auditmanager.go
> Fix static analysis and formatting

- artifactory/commands/transferfiles/filesdiff.go
- artifactory/commands/transferfiles/fileserror.go
- artifactory/commands/transferfiles/fulltransfer.go
- artifactory/commands/transferfiles/manager.go
- artifactory/commands/transferfiles/state/state.go
- artifactory/commands/transferfiles/state/statemanager.go
- artifactory/commands/transferfiles/state/timeestimation_test.go
- artifactory/commands/transferfiles/transfer.go
- artifactory/commands/transferfiles/transferfileprogress.go
- utils/progressbar/progressbarmng.go
- utils/progressbar/transferprogressbarmanager.go
> Enhancements to the progress bars code

- xray/utils/resultstable.go
> Unreleased Bug - Gitlab Audit

- artifactory/commands/npm/installorci.go
-----
Print full npm install command including command args
following https://github.com/jfrog/jfrog-cli/issues/1822
> Improve npm install command log

- .github/workflows/test.yml
- artifactory/utils/container/containermanager.go
- artifactory/utils/dependenciesutils.go
- missioncontrol/utils/missioncontrolutils_test.go
- xray/audit/python/python.go
- xray/audit/python/python_test.go
- xray/commands/testdata/pip-project/requirementsproject/requirements.txt
-----
following https://github.com/jfrog/frogbot/issues/265
> Fix pip requirements install and replace 'pip' with 'python -m pip'

- artifactory/commands/transferfiles/utils.go
> Transfer - Add logs for threads polling

- xray/commands/audit/generic/auditmanager.go
> Fix audit multiple technologies issue

- artifactory/utils/container/localagent.go
> Add more logs to docker

- .github/workflows/cla.yml
- artifactory/utils/projectconfig.go
- go.mod
- go.sum
> Fix CLA trigger

- go.mod
- go.sum
- xray/audit/commonutils.go
- xray/audit/commonutils_test.go
- xray/commands/audit/generic/auditmanager.go
-----
- Send a flat graph to XRay before scanning.
- Receive a list of vulnerable dependencies.
- Build the impact paths for each vulnerable dependency.
> Flatten audit graph

- artifactory/commands/transferfiles/delayedartifactshandler.go
- artifactory/commands/transferfiles/errorshandler.go
- xray/audit/java/gradle.go
> Fix Gradle audit access token handling

- artifactory/commands/transferfiles/fulltransfer.go
- artifactory/commands/transferfiles/transferfileprogress.go
- go.mod
- go.sum
- pipelines/commands/status.go
- pipelines/commands/version.go
- utils/lock/utils_unix.go
- utils/progressbar/transferprogressbarmanager.go
- xray/audit/java/gradle.go
- xray/commands/audit/generic/auditmanager.go
> Audit - Log the list of flattened dependencies in debug

- go.mod
- go.sum
- utils/config/tokenrefresh.go
-----
Adapt https://github.com/jfrog/jfrog-client-go/pull/729
This PR **does not** add support for reference tokens in the JFrog CLI.
> Add compatibility to include reference tokens

- artifactory/commands/utils/transferconfigbase.go
> Simplify assignment in removeFederatedMembers

- utils/coreutils/cmdutils.go
> Fix wrong threads flag extracting for docker commands

- xray/commands/audit/generic/auditmanager.go
>  Audit - Fix missing params.dependencyTrees field

- xray/utils/resultstable.go
-----
When there are no CVEs returning from the scan, we try to access cves[0] which is nil.
> Fix Cves NPE

- artifactory/commands/transferconfig/transferconfig.go
> Transfer config - change export dir permissions

- artifactory/commands/npm/npmcommand.go
- xray/audit/commonutils.go
- xray/commands/audit/generic/auditmanager.go
- xray/commands/audit/generic/generic.go
- xray/commands/curation/audit.go
- xray/utils/models.go
-----
- Fix the "Direct Dependency" column in the audit results.
- Restructure the AuditParams parameters.
> Audit - fix wrong direct dependency and params restructure

- .github/workflows/analysis.yml
- .github/workflows/frogbot-scan-and-fix.yml
- .github/workflows/test.yml
> Avoid running tests and static analysis on tags

- xray/utils/resultwriter.go
> Audit JSON update to retrieve only Xray results

- artifactory/commands/buildinfo/buildappend.go
- artifactory/utils/dependenciesutils.go
- go.mod
- go.sum
> Handle empty response from GetRemoteFileDetails

- go.mod
- go.sum
> Update jfrog-client-go to 1.29.1

- artifactory/utils/dependenciesutils.go
> Make the "DownloadDependency" utility public 

- xray/audit/npm/npm.go
> Infinite loop while parsing Npm dependency list

- xray/audit/npm/npm_test.go
-----
Fix expected tree on TestParseNpmDepedencies function
> Fix Npm parse tree test

- xray/audit/yarn/yarn.go
- xray/audit/yarn/yarn_test.go
-----
Fixed the Xray ID generated for the root of scoped packages. This issue caused scanning scoped Yarn projects to fail.
> Scanning scoped Yarn projects failed

- xray/commands/audit/generic/auditmanager.go
- xray/commands/audit/generic/generic.go
- xray/utils/analyzermanager.go
-----
This PR adds a minimal Xray version validation in `Jf audit `command flow to prevent the following error:
` [Error] failed while attempting to get Xray entitlements response for contextual_analysis:`
> Fix `Jf Audit` command entitlements service error

- utils/coreutils/utils.go
> Contextual analysis - add arm64 arch support

- artifactory/commands/transferfiles/fulltransfer.go
-----
Before this change, delayed files were tracked in the transfer repository snapshot (by incrementing the files count). This could block potential tree collapsing in the snapshot tree, since the directories containing those files would only be completed in later stage. Not collapsing the tree could in turn cause an increase in memory.
> Transfer - Disable repo snapshot for delayed files

- artifactory/utils/dependenciesutils.go
> Remove redundant space in download dependency log

- artifactory/utils/utils.go
- go.mod
- go.sum
- lifecycle/common.go
- lifecycle/createcommon.go
- lifecycle/createfrombuilds.go
- lifecycle/createfrombundles.go
- lifecycle/promote.go
- utils/config/config.go
-----
Add support for the new functionality of Release Bundles  as part of JFrog Release Lifecycle Management
Depends on https://github.com/jfrog/jfrog-client-go/pull/758
> Add Support for Release Bundles Create and Promote

- artifactory/utils/weblogin.go
- common/commands/config.go
- common/commands/config_test.go
- general/envsetup/envsetup.go
- general/login/login.go
- general/utils.go
- general/utils_test.go
- go.mod
- go.sum
- utils/config/config.go
-----
Depends on https://github.com/jfrog/jfrog-client-go/pull/785
Will become available once Artifactory 7.63.1 is released to self-hosted
> Add support for Web Login

- artifactory/commands/repository/repository.go
- artifactory/commands/repository/template.go
- artifactory/commands/utils/questionnaire.go
- artifactory/commands/utils/templateutils.go
-----
Adds the `environments` option to the `jf rt rpt` command
> Support environments in repository creation

- artifactory/utils/container/buildinfo_test.go
- xray/audit/jas/applicabilitymanager_test.go
- xray/audit/jas/jasmanager.go
- xray/audit/jas/jasmanager_test.go
- xray/commands/audit/generic/auditmanager.go
- xray/utils/models.go
> Add progress bar to JFrog Advanced Security scanners

- artifactory/utils/weblogin.go
- common/commands/config.go
- general/login/login.go
-----
1. When configuring a new server, do not suggest default values from the default server.
2. When logging in to an existing server, avoid all prompts if possible.
3. Minor wording changes.
> Web login and config improvements

- utils/coreutils/cmdutils.go
- utils/coreutils/tableutils.go
- xray/utils/resultstable.go
- xray/utils/resultwriter.go
> Improve Audit table results view

- artifactory/utils/weblogin.go
> Improve Web Login Logs

- xray/audit/jas/applicabilitymanager.go
- xray/audit/jas/applicabilitymanager_test.go
- xray/audit/jas/jasmanager.go
- xray/audit/jas/jasmanager_test.go
- xray/commands/audit/generic/auditmanager.go
- xray/commands/audit/generic/auditmanager_test.go
- xray/commands/curation/audit.go
- xray/utils/models.go
> Fix Python Contextual analysis missing dependencies issue

- go.mod
- go.sum
> update build-info-go dependency

- xray/audit/jas/jasmanager.go
- xray/utils/analyzermanager.go
- xray/utils/resultstable.go
- xray/utils/sarifutils.go
-----
Fix: inserting the value of the converted result to the list before handling the specific scan changes
> Fix sarif convert

- xray/utils/analyzermanager.go
-----
Update AnalyzerManager version to v1.3.2.2005632  that allows to run Sast scans
> Sast advance scan

- go.mod
- go.sum
- utils/config/tokenrefresh.go
-----
Depends on https://github.com/jfrog/jfrog-client-go/pull/830
> Rename tokens refresh thresholds

- artifactory/commands/transferfiles/delayedartifactshandler.go
> Transfer - pom.xml files should also be delayed

- xray/utils/resultstable.go
-----
Fix bug not showing Sast findings from [https://github.com/jfrog/jfrog-cli-core/pull/927](https://github.com/jfrog/jfrog-cli-core/pull/927)
> Show findings in Sast

- artifactory/commands/transferfiles/delayedartifactshandler.go
- artifactory/commands/transferfiles/fulltransfer.go
- artifactory/commands/transferfiles/state/runstatus.go
- artifactory/commands/transferfiles/state/statemanager.go
- artifactory/commands/transferfiles/state/statemanager_test.go
- artifactory/commands/transferfiles/status.go
- artifactory/commands/transferfiles/status_test.go
- artifactory/commands/transferfiles/transfer.go
- artifactory/commands/transferfiles/transferfileprogress.go
- utils/progressbar/transferprogressbarmanager.go
> Transfer - Show visited folders counter

- utils/progressbar/progressbarmng.go
- utils/progressbar/transferprogressbarmanager.go
-----
Fix the following issues of the `transfer-files` progressbar:
1. The progress in phase 1 never gets filled
2. The label in phase 3 is wrong
> Transfer - Fix some issues in the progressbar

- artifactory/commands/npm/publish.go
- go.mod
- go.sum
- xray/commands/audit/sca/npm/npm.go
- xray/commands/audit/sca/yarn/yarn.go
-----
Depends on https://github.com/jfrog/build-info-go/pull/206
Dependency for https://github.com/jfrog/jfrog-cli/pull/2269
> Support running npm install without package.json

- go.mod
- go.sum
> Upgrade jfrog-cli-core to 2.45.4

- xray/commands/audit/sca/npm/npm.go
> Improvement to an error message

- artifactory/commands/buildinfo/buildappend.go
- go.mod
- go.sum
-----
Fix https://github.com/jfrog/jfrog-cli/issues/1803 & https://github.com/jfrog/jfrog-cli/issues/2043
Depends on https://github.com/jfrog/jfrog-client-go/pull/854
> Build append fails with special characters

- utils/coreutils/techutils.go
> New Yarn tech detection indicator

- xray/utils/resultwriter.go
Reverts jfrog/jfrog-cli-core#1047
> Revert "Enhancements in Output Control Options for Scan Results Writer"

- xray/commands/audit/sca/go/gloang_test.go
- xray/commands/audit/sca/go/golang.go
- xray/commands/audit/sca/npm/npm.go
- xray/commands/audit/sca/nuget/nuget.go
- xray/commands/audit/sca/yarn/yarn.go
- xray/commands/audit/sca/yarn/yarn_test.go
- xray/commands/audit/scarunner.go
-----
Logs were added when resolving dependencies from an Artifactory server
Yarn flow was simplified to better understand the flow
Tests were fixed according to changes
> Refactor- added logs and simplified flow

- xray/utils/analyzermanager.go
> Upgraded analyzer manager to version 1.6.0

- artifactory/utils/weblogin.go
-----
Include the necessary verification code to finalize the Single Sign-On (SSO) login process on the JFrog platform website.
> WebLogin - Add verification code

- xray/utils/analyzermanager.go
> Analyzer manager updated to version 1.6.3

- artifactory/commands/npm/npmcommand.go
- artifactory/commands/npm/npmcommand_test.go
- common/project/projectconfig.go
- tests/testdata/npm-project/helloworld.js
- tests/testdata/npm-project/package.json
- utils/java/deptreemanager.go
- utils/java/mvn.go
- utils/java/mvn_test.go
> Upgrade jfrog-cli-core to 2.47.12

- go.mod
- go.sum
- lifecycle/createfrombuilds.go
-----
Depends on https://github.com/jfrog/jfrog-client-go/pull/895
> Artifactory Release Lifecycle Management - Add include dependencies option to release bundle creation

- .github/workflows/analysis.yml
-----
There is a bug at 2.19 for ignore on multiple lines:
When:
> Use Go-Sec 2.18.0

- common/project/projectconfig.go
-----
Add `pnpm` as a new type to allow option to add config file for this package-manager
> Add Pnpm as project type for config

- go.mod
- go.sum
> Upgrade jfrog-cli-core to 2.48.1

- common/commands/configfile.go
-----
Fix a copy paste error - SnapshotsRepo copied twice
> Fix interactive Maven config command

- go.mod
- go.sum
-----
Include https://github.com/jfrog/gofrog/pull/54
> Fix false positive ZipSlip when an archive starts with dot

- plugins/components/conversionlayer.go
- plugins/components/conversionlayer_test.go
> Duplicate App Name at plugins help usage

- artifactory/commands/generic/upload.go
- artifactory/commands/transferfiles/utils.go
- artifactory/utils/storageinfo.go
- artifactory/utils/storageinfo_test.go
- artifactory/utils/upload.go
- go.mod
- go.sum
- utils/progressbar/progressbarmng.go
-----
Depends on https://github.com/jfrog/jfrog-client-go/pull/936
> Support providing chunk size in multi part upload

- utils/coreutils/techutils.go
-----
https://en.wikipedia.org/wiki/Open_Container_Initiative
OCI: https://opencontainers.org/
> Add OCI technology

- go.mod
- go.sum
> Update version to 2.52.0

- artifactory/utils/utils.go
- go.mod
- go.sum
- utils/config/config.go
> Support evidence service

- common/commands/configfile.go
> Fix terraform interactive config

- artifactory/utils/weblogin.go
-----
The JFrog CLI prompts users to enter a code in the browser that opens, but the code’s visibility is insufficient.
Before:
After:
> Web login - Make the uuid bold in green

- go.mod
- go.sum
> Upgrade jfrog-cli-core to 2.53.3

- .github/workflows/analysis.yml
- .github/workflows/cla.yml
- .github/workflows/frogbot-scan-pull-request.yml
- .github/workflows/frogbot-scan-repository.yml
- .github/workflows/test.yml
-----
https://github.com/jfrog/.github
> Unite all common GitHub action steps

- plugins/components/conversionlayer.go
- plugins/components/structure.go
-----
Add an option for a plugin to create a hidden `Namespace`
> Add hidden option for namespace

- go.mod
- go.sum
> Upgrade to 2.54.0

- go.mod
- go.sum
> Upgrade jfrog-cli-core to 2.54.1

- common/progressbar/filesprogressbar.go
> Files Progress Bar - remove unnecessary nil assignment

- go.mod
- go.sum
> Upgrade jfrog-cli-core to 2.55.5

- go.mod
- go.sum
> Upgrade jfrog-cli-core to 2.55.6

- artifactory/utils/commandsummary/buildinfosummary.go
- artifactory/utils/commandsummary/commandsummary.go
- artifactory/utils/commandsummary/markdownConfig.go
- artifactory/utils/testdata/command_summaries/basic/build-info-table.md
- artifactory/utils/testdata/command_summaries/basic/docker-image-module.md
- artifactory/utils/testdata/command_summaries/basic/generic-module.md
- artifactory/utils/testdata/command_summaries/basic/maven-module.md
- artifactory/utils/testdata/command_summaries/basic/multiarch-docker-image.md
-----
Also add some debug logs for easier debugging.
> Update Summaries extended page link & Add logs

- artifactory/utils/commandsummary/commandsummary.go
- artifactory/utils/commandsummary/commandsummary_test.go
> Make command summary util available

- utils/dependencies/utils.go
> Fix path to build info JARs documentation

- go.mod
- go.sum
- utils/mvn/utils.go
-----
Depends on https://github.com/jfrog/build-info-go/pull/279
Fix https://github.com/jfrog/jfrog-cli/issues/2673
> Recursively search for the .mvn directpry

- common/commands/configfile.go
- common/project/projectconfig.go
Replaces https://github.com/jfrog/jfrog-cli-core/pull/1274
-----
> Cocoapods config for Artifactory repositories

- common/commands/configfile.go
- common/project/projectconfig.go
> Prep code for a `jf audit` command for Swift

- artifactory/commands/dotnet/dotnetcommand.go
- artifactory/commands/dotnet/dotnetcommand_test.go
> FIx Nuget & DotNet tests

- utils/usage/visibility_system_manager.go
> Fix visibility system calling

- go.mod
-----
Will be handled separately. and upgraded with the CLI
> Downgrade Go version

- artifactory/utils/commandsummary/commandsummary.go
-----
Add index of Evidences to allow recording.
this was extracted from the following pr : https://github.com/jfrog/jfrog-cli-core/pull/1323
in order to allow recording of the evidences, but until the design will be final the full PR shouldn't be merged.
> Job Summary - Add Evidence recording index

- common/cliutils/spec.go
- plugins/common/utils.go
- plugins/components/commandcomp.go
- plugins/components/conversionlayer.go
- utils/coreutils/coreconsts.go
-----
depends on :-
1. https://github.com/jfrog/jfrog-cli/pull/2936
2. https://github.com/jfrog/jfrog-cli-artifactory/pull/58
> Rt cmd migration

- go.mod
- go.sum
> Promote Version to v`2.58.3`

- go.mod
- go.sum
> Introduced support for lifecycle annotate command

- common/project/projectconfig.go
> Add Helm to ProjectTypes and ProjectType constants

- artifactory/utils/weblogin.go
> Display weblogin URL in the terminal

- go.mod
- go.sum
- utils/coreutils/tableutils.go
-----
What: Update go.mod and go.sum and reset header just to remove Key, Value itself in top.
> Updating mod and sum temp
